// Copyright (c) 2026.The Cloth contributors.
// 
// LlvmEmitter.cs is part of the Cloth Compiler.
// 
// Use, modification, and distribution of this file are governed by the
// license terms provided with the Cloth Compiler source distribution.

using System.Globalization;
using System.Text;
using Compiler.CIR;

namespace Compiler.LLVM;

// Lowers a CirModule to LLVM IR text (.ll) and writes it to {projectRoot}/build/{ProjectName}.ll.
// Uses LLVM 15+ opaque-pointer style and the alloca/load/store pattern for all locals;
// `mem2reg` (run by clang) promotes them to SSA.
public sealed class LlvmEmitter {
	private readonly CirModule _module;
	private readonly BuildConfig _config;
	private readonly string _projectRoot;

	private readonly Dictionary<string, CirTypeDecl.Class> _classByFqn = new();
	private readonly HashSet<string> _definedFns = new();
	private readonly Dictionary<string, string> _externDecls = new();

	private readonly List<string> _strings = new();
	private readonly Dictionary<string, int> _stringIndex = new();

	// CirFunctions whose IsExtern == true. Keyed by MangledName (already the literal C symbol
	// for @Extern declarations). Provides proper signatures for `declare` lines.
	private readonly Dictionary<string, CirFunction> _externFns = new();

	// Per-function state
	private int _tempCounter;
	private string _currentThisFqn = "";
	private CirType _currentReturnType = new CirType.Void();
	private readonly List<string> _allocaLines = new();
	private readonly List<string> _prologueLines = new();
	private readonly List<string> _bodyLines = new();
	private bool _blockTerminated;
	private readonly Dictionary<string, string> _localAddrMap = new();
	private readonly Dictionary<string, CirType> _localTypeMap = new();

	public LlvmEmitter(CirModule module, BuildConfig config, string projectRoot) {
		_module = module;
		_config = config;
		_projectRoot = projectRoot;

		foreach (var t in _module.Types)
			if (t is CirTypeDecl.Class c)
				_classByFqn[c.FullyQualifiedName] = c;
	}

	public string Emit() {
		var llText = Build();
		var buildDir = Path.Combine(_projectRoot, "build");
		Directory.CreateDirectory(buildDir);
		var llPath = Path.Combine(buildDir, _config.ProjectName + ".ll");
		File.WriteAllText(llPath, llText, new UTF8Encoding(false));
		return llPath;
	}

	// -------------------------------------------------------------------------
	// Module assembly
	// -------------------------------------------------------------------------

	private string Build() {
		PreScan();

		var sb = new StringBuilder();
		sb.AppendLine("; Generated by the Cloth Compiler");
		sb.AppendLine($"source_filename = \"{_config.ProjectName}\"");
		sb.AppendLine("target datalayout = \"e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128\"");
		sb.AppendLine($"target triple = \"{ResolveTriple(_config.Target)}\"");
		sb.AppendLine();

		var types = EmitStructTypes();
		if (types.Length > 0) {
			sb.Append(types);
			sb.AppendLine();
		}

		var strs = EmitStringGlobals();
		if (strs.Length > 0) {
			sb.Append(strs);
			sb.AppendLine();
		}

		var externs = EmitExternDecls();
		if (externs.Length > 0) {
			sb.Append(externs);
			sb.AppendLine();
		}

		foreach (var fn in _module.Functions) {
			if (fn.IsExtern) continue;
			sb.Append(EmitFunction(fn));
			sb.AppendLine();
		}

		if (_config.Output == "executable")
			sb.Append(EmitMainEntry());
		return sb.ToString();
	}

	private static string ResolveTriple(string target) => target switch {
		"x64_86" or "x86_64" or "" => "x86_64-pc-windows-msvc",
		"x86" => "i686-pc-windows-msvc",
		"arm64" => "aarch64-pc-windows-msvc",
		_ => "x86_64-pc-windows-msvc"
	};

	// -------------------------------------------------------------------------
	// Pre-scan: collect defined functions, string literals, extern call targets
	// -------------------------------------------------------------------------

	private void PreScan() {
		foreach (var fn in _module.Functions) {
			if (fn.IsExtern) {
				_externFns[fn.MangledName] = fn;
				// Pre-populate _externDecls so call-site inference doesn't override the proper signature.
				var retTy = LlvmType(fn.ReturnType);
				var argSig = string.Join(", ", fn.Parameters.Select(p => LlvmType(p.Type)));
				_externDecls[fn.MangledName] = $"declare {retTy} @{fn.MangledName}({argSig})";
			}
			else {
				_definedFns.Add(fn.MangledName);
			}
		}

		foreach (var fn in _module.Functions) {
			foreach (var stmt in fn.Body)
				ScanStmt(stmt);
		}

		foreach (var t in _module.Types) {
			if (t is CirTypeDecl.Class c)
				foreach (var f in c.Fields)
					if (f.Initializer != null)
						ScanExpr(f.Initializer);
		}
	}

	private void ScanStmt(CirStmt stmt) {
		switch (stmt) {
			case CirStmt.LocalDecl d:
				if (d.Init != null) ScanExpr(d.Init);
				break;
			case CirStmt.TupleDecl t:
				ScanExpr(t.Init);
				break;
			case CirStmt.Assign a:
				ScanExpr(a.Target);
				ScanExpr(a.Value);
				break;
			case CirStmt.Expr e: ScanExpr(e.Expression); break;
			case CirStmt.Discard d: ScanExpr(d.Expression); break;
			case CirStmt.Return r:
				if (r.Value != null) ScanExpr(r.Value);
				break;
			case CirStmt.If i:
				ScanExpr(i.Condition);
				foreach (var s in i.Then) ScanStmt(s);
				foreach (var (c, b) in i.ElseIfs) {
					ScanExpr(c);
					foreach (var s in b) ScanStmt(s);
				}

				if (i.Else != null)
					foreach (var s in i.Else)
						ScanStmt(s);
				break;
			case CirStmt.While w:
				ScanExpr(w.Condition);
				foreach (var s in w.Body) ScanStmt(s);
				break;
			case CirStmt.DoWhile dw:
				foreach (var s in dw.Body) ScanStmt(s);
				ScanExpr(dw.Condition);
				break;
			case CirStmt.For f:
				ScanStmt(f.Init);
				ScanExpr(f.Condition);
				ScanExpr(f.Iterator);
				foreach (var s in f.Body) ScanStmt(s);
				break;
			case CirStmt.ForIn fi:
				ScanExpr(fi.Iterable);
				foreach (var s in fi.Body) ScanStmt(s);
				break;
			case CirStmt.Switch sw:
				ScanExpr(sw.Subject);
				foreach (var c in sw.Cases) {
					if (c.Pattern != null) ScanExpr(c.Pattern);
					foreach (var s in c.Body) ScanStmt(s);
				}

				break;
			case CirStmt.Throw t: ScanExpr(t.Expression); break;
			case CirStmt.Delete d: ScanExpr(d.Expression); break;
			case CirStmt.Block b:
				foreach (var s in b.Body) ScanStmt(s);
				break;
		}
	}

	private void ScanExpr(CirExpr expr) {
		switch (expr) {
			case CirExpr.StrLit s:
				if (!_stringIndex.ContainsKey(s.Value)) {
					_stringIndex[s.Value] = _strings.Count;
					_strings.Add(s.Value);
				}

				break;
			case CirExpr.Binary b:
				ScanExpr(b.Left);
				ScanExpr(b.Right);
				break;
			case CirExpr.Unary u: ScanExpr(u.Operand); break;
			case CirExpr.FieldAccess fa: ScanExpr(fa.Target); break;
			case CirExpr.Index i:
				ScanExpr(i.Target);
				ScanExpr(i.Idx);
				break;
			case CirExpr.Call c:
				if (!_definedFns.Contains(c.MangledName))
					RecordExternCall(c.MangledName, c.Args.Count);
				foreach (var a in c.Args) ScanExpr(a);
				break;
			case CirExpr.IndirectCall ic:
				ScanExpr(ic.Callee);
				foreach (var a in ic.Args) ScanExpr(a);
				break;
			case CirExpr.Alloc a:
				if (!_definedFns.Contains(a.CtorMangledName))
					RecordExternCall(a.CtorMangledName, a.Args.Count + 1);
				foreach (var x in a.Args) ScanExpr(x);
				break;
			case CirExpr.Cast c: ScanExpr(c.Value); break;
			case CirExpr.TypeCheck t: ScanExpr(t.Value); break;
			case CirExpr.Ternary t:
				ScanExpr(t.Condition);
				ScanExpr(t.Then);
				ScanExpr(t.Else);
				break;
			case CirExpr.NullCoalesce n:
				ScanExpr(n.Left);
				ScanExpr(n.Right);
				break;
			case CirExpr.TupleLit t:
				foreach (var e in t.Elements) ScanExpr(e);
				break;
			case CirExpr.Range r:
				ScanExpr(r.Start);
				ScanExpr(r.End);
				break;
		}
	}

	private void RecordExternCall(string cirName, int argCount) {
		var llvmName = MangleToLlvm(cirName);
		if (_externDecls.ContainsKey(llvmName)) return;
		var args = string.Join(", ", Enumerable.Repeat("ptr", argCount));
		_externDecls[llvmName] = $"declare void @{llvmName}({args})";
	}

	// -------------------------------------------------------------------------
	// Sections
	// -------------------------------------------------------------------------

	private string EmitStructTypes() {
		var sb = new StringBuilder();
		foreach (var t in _module.Types) {
			if (t is not CirTypeDecl.Class c) continue;
			var name = StructName(c.FullyQualifiedName);
			if (c.Fields.Count == 0) {
				sb.AppendLine($"{name} = type {{ ptr }}");
				continue;
			}

			var fieldTypes = string.Join(", ", c.Fields.Select(f => LlvmType(f.Type)));
			sb.AppendLine($"{name} = type {{ {fieldTypes} }}");
		}

		return sb.ToString();
	}

	private string EmitStringGlobals() {
		var sb = new StringBuilder();
		for (var i = 0; i < _strings.Count; i++) {
			var (encoded, byteCount) = EncodeStringConstant(_strings[i]);
			sb.AppendLine($"@.str.{i} = private unnamed_addr constant [{byteCount} x i8] c\"{encoded}\", align 1");
		}

		return sb.ToString();
	}

	private string EmitExternDecls() {
		var sb = new StringBuilder();
		foreach (var line in _externDecls.Values)
			sb.AppendLine(line);
		return sb.ToString();
	}

	// -------------------------------------------------------------------------
	// Functions
	// -------------------------------------------------------------------------

	private string EmitFunction(CirFunction fn) {
		_tempCounter = 0;
		_currentThisFqn = "";
		_currentReturnType = fn.ReturnType;
		_allocaLines.Clear();
		_prologueLines.Clear();
		_bodyLines.Clear();
		_blockTerminated = false;
		_localAddrMap.Clear();
		_localTypeMap.Clear();

		var llvmName = MangleToLlvm(fn.MangledName);
		var paramSigParts = new List<string>();
		foreach (var p in fn.Parameters) {
			var ty = LlvmType(p.Type);
			paramSigParts.Add($"{ty} %{p.Name}");

			var addr = $"%{p.Name}.addr";
			_allocaLines.Add($"  {addr} = alloca {ty}, align 8");
			_prologueLines.Add($"  store {ty} %{p.Name}, ptr {addr}");
			_localAddrMap[p.Name] = addr;
			_localTypeMap[p.Name] = p.Type;

			if (p.Name == "this" && p.Type is CirType.Ptr ptr && ptr.Inner is CirType.Named named)
				_currentThisFqn = named.FullyQualifiedName;
		}

		var retTy = LlvmType(fn.ReturnType);
		var paramSig = string.Join(", ", paramSigParts);

		foreach (var stmt in fn.Body)
			EmitStmt(stmt);

		if (!_blockTerminated) {
			_bodyLines.Add(fn.ReturnType is CirType.Void ? "  ret void" : $"  ret {retTy} {DefaultValue(fn.ReturnType)}");
		}

		var sb = new StringBuilder();
		sb.AppendLine($"define {retTy} @{llvmName}({paramSig}) {{");
		sb.AppendLine("entry:");
		foreach (var line in _allocaLines) sb.AppendLine(line);
		foreach (var line in _prologueLines) sb.AppendLine(line);
		foreach (var line in _bodyLines) sb.AppendLine(line);
		sb.AppendLine("}");
		return sb.ToString();
	}

	private string EmitMainEntry() {
		var mainCtor = FindMainCtor();
		if (mainCtor == null) {
			if (_config.Output == "executable")
				LlvmError.NoEntryPoint.WithMessage($"project '{_config.ProjectName}' has output=executable but no class defines a constructor accepting 'args'").Render();
			return "";
		}

		var thisParam = mainCtor.Parameters[0];
		var thisFqn = ((CirType.Named)((CirType.Ptr)thisParam.Type).Inner).FullyQualifiedName;
		var structName = StructName(thisFqn);
		var ctorLlvm = MangleToLlvm(mainCtor.MangledName);

		// Find a matching destructor (mangled name ends with .~ClassName)
		var className = thisFqn.Contains('.') ? thisFqn[(thisFqn.LastIndexOf('.') + 1)..] : thisFqn;
		var dtorCir = $"{thisFqn}.~{className}";
		var dtorLlvm = _definedFns.Contains(dtorCir) ? MangleToLlvm(dtorCir) : null;

		var sb = new StringBuilder();
		sb.AppendLine("define i32 @main(i32 %argc, ptr %argv) {");
		sb.AppendLine("entry:");
		sb.AppendLine($"  %instance = alloca {structName}, align 8");
		// Pass argv as the 'args' parameter (opaque ptr — runtime conversion is a future concern).
		sb.AppendLine($"  call void @{ctorLlvm}(ptr %instance, ptr %argv)");
		if (dtorLlvm != null)
			sb.AppendLine($"  call void @{dtorLlvm}(ptr %instance)");
		sb.AppendLine("  ret i32 0");
		sb.AppendLine("}");
		return sb.ToString();
	}

	private CirFunction? FindMainCtor() {
		// Pick the first constructor whose explicit parameters include 'args'.
		foreach (var fn in _module.Functions) {
			if (fn.Kind != CirFunctionKind.Constructor) continue;
			// Parameters[0] is always 'this'; look for another named 'args'.
			for (var i = 1; i < fn.Parameters.Count; i++)
				if (fn.Parameters[i].Name == "args")
					return fn;
		}

		return null;
	}

	// -------------------------------------------------------------------------
	// Statements
	// -------------------------------------------------------------------------

	private void EmitStmt(CirStmt stmt) {
		switch (stmt) {
			case CirStmt.LocalDecl d: EmitLocalDecl(d); break;
			case CirStmt.Assign a: EmitAssign(a); break;
			case CirStmt.Expr e: EmitExprStmt(e.Expression); break;
			case CirStmt.Discard d: EmitExprStmt(d.Expression); break;
			case CirStmt.Return r: EmitReturn(r); break;
			case CirStmt.Block b:
				foreach (var s in b.Body) EmitStmt(s);
				break;
			default:
				LlvmError.UnsupportedStatement.WithMessage($"{stmt.GetType().Name} is not yet lowerable to LLVM IR").Render();
				break;
		}
	}

	private void EmitLocalDecl(CirStmt.LocalDecl d) {
		var ty = d.Type ?? new CirType.Any();
		var llvmTy = LlvmType(ty);
		var addr = $"%{d.Name}.addr";
		_allocaLines.Add($"  {addr} = alloca {llvmTy}, align 8");
		_localAddrMap[d.Name] = addr;
		_localTypeMap[d.Name] = ty;

		if (d.Init != null) {
			var val = EmitExpr(d.Init);
			_bodyLines.Add($"  store {llvmTy} {val}, ptr {addr}");
		}
	}

	private void EmitAssign(CirStmt.Assign a) {
		var addr = EmitAddrOf(a.Target);
		var (targetTy, _) = TypeOfLvalue(a.Target);
		var llvmTy = LlvmType(targetTy);
		var rhs = EmitExpr(a.Value);

		if (a.Op == CirAssignOp.Assign) {
			_bodyLines.Add($"  store {llvmTy} {rhs} , ptr {addr}".Replace(" , ", ", "));
		}
		else {
			var loaded = FreshTemp();
			_bodyLines.Add($"  {loaded} = load {llvmTy}, ptr {addr}");
			var op = AssignToBinOp(a.Op);
			var combined = FreshTemp();
			_bodyLines.Add($"  {combined} = {LlvmBinOp(op, llvmTy)} {llvmTy} {loaded}, {rhs}");
			_bodyLines.Add($"  store {llvmTy} {combined}, ptr {addr}");
		}
	}

	private void EmitExprStmt(CirExpr expr) {
		// Calls and other side-effecting expressions; emit and discard.
		_ = EmitExpr(expr);
	}

	private void EmitReturn(CirStmt.Return r) {
		if (r.Value == null) {
			_bodyLines.Add("  ret void");
		}
		else {
			var val = EmitExpr(r.Value);
			_bodyLines.Add($"  ret {LlvmType(_currentReturnType)} {val}");
		}

		_blockTerminated = true;
	}

	// -------------------------------------------------------------------------
	// Expressions
	// -------------------------------------------------------------------------

	// Returns the SSA name (e.g. "%_t3") or literal (e.g. "42") representing the value.
	private string EmitExpr(CirExpr expr) {
		switch (expr) {
			case CirExpr.IntLit i: return i.Value;
			case CirExpr.FloatLit f: return f.Value;
			case CirExpr.BoolLit b: return b.Value ? "1" : "0";
			case CirExpr.CharLit c: return ((int)c.Value).ToString(CultureInfo.InvariantCulture);
			case CirExpr.StrLit s: return InternString(s.Value);
			case CirExpr.NullLit: return "null";

			case CirExpr.Local l: return EmitLocalLoad(l.Name);
			case CirExpr.ThisPtr: return EmitLocalLoad("this");

			case CirExpr.FieldAccess fa: return EmitFieldLoad(fa);
			case CirExpr.Call c: return EmitCall(c);

			case CirExpr.Binary b: return EmitBinary(b);
			case CirExpr.Unary u: return EmitUnary(u);
		}

		LlvmError.UnsupportedExpression.WithMessage($"{expr.GetType().Name} is not yet lowerable to LLVM IR").Render();
		return "undef";
	}

	private string EmitLocalLoad(string name) {
		if (!_localAddrMap.TryGetValue(name, out var addr) || !_localTypeMap.TryGetValue(name, out var ty)) {
			LlvmError.UnsupportedExpression.WithMessage($"reference to unknown local '{name}'").Render();
			return "undef";
		}

		var t = FreshTemp();
		_bodyLines.Add($"  {t} = load {LlvmType(ty)}, ptr {addr}");
		return t;
	}

	private string EmitFieldLoad(CirExpr.FieldAccess fa) {
		var (gep, fieldType) = EmitFieldGep(fa);
		var t = FreshTemp();
		_bodyLines.Add($"  {t} = load {LlvmType(fieldType)}, ptr {gep}");
		return t;
	}

	private (string gep, CirType fieldType) EmitFieldGep(CirExpr.FieldAccess fa) {
		var targetVal = EmitExpr(fa.Target);
		var fqn = ResolveTargetFqn(fa.Target);
		if (fqn == null || !_classByFqn.TryGetValue(fqn, out var cls)) {
			LlvmError.FieldNotFound.WithMessage($"cannot resolve owning type of field '{fa.FieldName}'").Render();
			return ("undef", new CirType.Any());
		}

		var idx = cls.Fields.FindIndex(f => f.Name == fa.FieldName);
		if (idx < 0) {
			LlvmError.FieldNotFound.WithMessage($"field '{fa.FieldName}' not found on {fqn}").Render();
			return ("undef", new CirType.Any());
		}

		var gep = FreshTemp();
		_bodyLines.Add($"  {gep} = getelementptr inbounds {StructName(fqn)}, ptr {targetVal}, i32 0, i32 {idx}");
		return (gep, cls.Fields[idx].Type);
	}

	private string EmitCall(CirExpr.Call c) {
		var argVals = c.Args.Select(EmitExpr).ToList();
		// For @Extern targets, MangledName is already the literal C symbol — do not re-mangle.
		var llvmName = _externFns.ContainsKey(c.MangledName) ? c.MangledName : MangleToLlvm(c.MangledName);

		// Look up the called function's signature if it's defined locally; fall back to extern's "all ptr / void".
		var callee = _module.Functions.FirstOrDefault(f => f.MangledName == c.MangledName);
		string retTy;
		List<string> paramTys;
		if (callee != null) {
			retTy = LlvmType(callee.ReturnType);
			paramTys = callee.Parameters.Select(p => LlvmType(p.Type)).ToList();
		}
		else {
			retTy = "void";
			paramTys = Enumerable.Repeat("ptr", c.Args.Count).ToList();
		}

		var argList = string.Join(", ", argVals.Select((v, i) => $"{(i < paramTys.Count ? paramTys[i] : "ptr")} {v}"));

		if (retTy == "void") {
			_bodyLines.Add($"  call void @{llvmName}({argList})");
			return "void";
		}

		var t = FreshTemp();
		_bodyLines.Add($"  {t} = call {retTy} @{llvmName}({argList})");
		return t;
	}

	private string EmitBinary(CirExpr.Binary b) {
		var lhs = EmitExpr(b.Left);
		var rhs = EmitExpr(b.Right);
		// Defaulting to i32 arithmetic for now — proper type-aware lowering comes with a CIR type-checker pass.
		var t = FreshTemp();
		_bodyLines.Add($"  {t} = {LlvmBinOp(b.Op, "i32")} i32 {lhs}, {rhs}");
		return t;
	}

	private string EmitUnary(CirExpr.Unary u) {
		var operand = EmitExpr(u.Operand);
		var t = FreshTemp();
		switch (u.Op) {
			case CirUnOp.Neg:
				_bodyLines.Add($"  {t} = sub i32 0, {operand}");
				return t;
			case CirUnOp.Not:
				_bodyLines.Add($"  {t} = xor i1 {operand}, true");
				return t;
			case CirUnOp.BitNot:
				_bodyLines.Add($"  {t} = xor i32 {operand}, -1");
				return t;
		}

		LlvmError.UnsupportedExpression.WithMessage($"unary operator {u.Op} not yet lowered").Render();
		return "undef";
	}

	// Address-of for an lvalue expression (assignment target).
	private string EmitAddrOf(CirExpr expr) {
		switch (expr) {
			case CirExpr.Local l:
				if (_localAddrMap.TryGetValue(l.Name, out var addr)) return addr;
				LlvmError.UnsupportedExpression.WithMessage($"address-of unknown local '{l.Name}'").Render();
				return "undef";
			case CirExpr.FieldAccess fa: return EmitFieldGep(fa).gep;
		}

		LlvmError.UnsupportedExpression.WithMessage($"cannot take address of {expr.GetType().Name}").Render();
		return "undef";
	}

	private (CirType type, bool found) TypeOfLvalue(CirExpr expr) {
		switch (expr) {
			case CirExpr.Local l:
				return _localTypeMap.TryGetValue(l.Name, out var ty) ? (ty, true) : (new CirType.Any(), false);
			case CirExpr.FieldAccess fa:
				var fqn = ResolveTargetFqn(fa.Target);
				if (fqn != null && _classByFqn.TryGetValue(fqn, out var cls)) {
					var f = cls.Fields.FirstOrDefault(x => x.Name == fa.FieldName);
					if (f != null) return (f.Type, true);
				}

				return (new CirType.Any(), false);
		}

		return (new CirType.Any(), false);
	}

	private string? ResolveTargetFqn(CirExpr target) => target switch {
		CirExpr.ThisPtr => _currentThisFqn,
		CirExpr.Local l when _localTypeMap.TryGetValue(l.Name, out var ty) => ty is CirType.Ptr p && p.Inner is CirType.Named np ? np.FullyQualifiedName : ty is CirType.Named n ? n.FullyQualifiedName : null,
		_ => null
	};

	// -------------------------------------------------------------------------
	// String pool
	// -------------------------------------------------------------------------

	private string InternString(string value) {
		// Already collected during pre-scan.
		var idx = _stringIndex[value];
		var (_, byteCount) = EncodeStringConstant(value);
		var t = FreshTemp();
		_bodyLines.Add($"  {t} = getelementptr inbounds [{byteCount} x i8], ptr @.str.{idx}, i32 0, i32 0");
		return t;
	}

	private static (string encoded, int byteCount) EncodeStringConstant(string value) {
		var bytes = Encoding.UTF8.GetBytes(value);
		var sb = new StringBuilder(bytes.Length + 1);
		foreach (var b in bytes) {
			if (b == '\\' || b == '"' || b < 0x20 || b > 0x7e)
				sb.Append('\\').Append(b.ToString("X2"));
			else
				sb.Append((char)b);
		}

		sb.Append("\\00");
		return (sb.ToString(), bytes.Length + 1);
	}

	// -------------------------------------------------------------------------
	// Type / op mapping
	// -------------------------------------------------------------------------

	private static string LlvmType(CirType t) => t switch {
		CirType.Void => "void",
		CirType.Any => "ptr",
		CirType.Ptr => "ptr",
		CirType.Nullable n => LlvmType(n.Inner),
		CirType.Array => "ptr",
		CirType.Tuple => "ptr",
		CirType.Generic => "ptr",
		CirType.Named n => n.FullyQualifiedName switch {
			"string" => "ptr",
			"int" => "i32",
			"long" => "i64",
			"short" => "i16",
			"byte" => "i8",
			"sbyte" => "i8",
			"char" => "i8",
			"bool" => "i1",
			"float" => "float",
			"double" => "double",
			"void" => "void",
			"any" => "ptr",
			_ => "ptr"
		},
		_ => "ptr"
	};

	private static string DefaultValue(CirType t) => t switch {
		CirType.Named n when n.FullyQualifiedName is "int" or "long" or "short" or "byte" or "sbyte" or "char" => "0",
		CirType.Named n when n.FullyQualifiedName == "bool" => "0",
		CirType.Named n when n.FullyQualifiedName is "float" or "double" => "0.0",
		_ => "null"
	};

	private static string LlvmBinOp(CirBinOp op, string ty) {
		var isFloat = ty is "float" or "double";
		return op switch {
			CirBinOp.Add => isFloat ? "fadd" : "add",
			CirBinOp.Sub => isFloat ? "fsub" : "sub",
			CirBinOp.Mul => isFloat ? "fmul" : "mul",
			CirBinOp.Div => isFloat ? "fdiv" : "sdiv",
			CirBinOp.Rem => isFloat ? "frem" : "srem",
			CirBinOp.BitAnd or CirBinOp.And => "and",
			CirBinOp.BitOr or CirBinOp.Or => "or",
			CirBinOp.BitXor => "xor",
			CirBinOp.Shl => "shl",
			CirBinOp.Shr => "ashr",
			CirBinOp.Eq => isFloat ? "fcmp oeq" : "icmp eq",
			CirBinOp.NotEq => isFloat ? "fcmp one" : "icmp ne",
			CirBinOp.Lt => isFloat ? "fcmp olt" : "icmp slt",
			CirBinOp.LtEq => isFloat ? "fcmp ole" : "icmp sle",
			CirBinOp.Gt => isFloat ? "fcmp ogt" : "icmp sgt",
			CirBinOp.GtEq => isFloat ? "fcmp oge" : "icmp sge",
			_ => "add"
		};
	}

	private static CirBinOp AssignToBinOp(CirAssignOp op) => op switch {
		CirAssignOp.AddAssign => CirBinOp.Add,
		CirAssignOp.SubAssign => CirBinOp.Sub,
		CirAssignOp.MulAssign => CirBinOp.Mul,
		CirAssignOp.DivAssign => CirBinOp.Div,
		CirAssignOp.RemAssign => CirBinOp.Rem,
		CirAssignOp.AndAssign => CirBinOp.BitAnd,
		CirAssignOp.OrAssign => CirBinOp.BitOr,
		CirAssignOp.XorAssign => CirBinOp.BitXor,
		_ => CirBinOp.Add
	};

	// -------------------------------------------------------------------------
	// Name mangling helpers
	// -------------------------------------------------------------------------

	private static string MangleToLlvm(string cirName) {
		var parts = cirName.Split('.');
		for (var i = 0; i < parts.Length; i++)
			if (parts[i].StartsWith('~'))
				parts[i] = "dtor_" + parts[i][1..];
		return string.Join('_', parts);
	}

	private static string StructName(string fqn) => "%struct." + MangleToLlvm(fqn);

	private string FreshTemp() => $"%_t{_tempCounter++}";
}