// Copyright (c) 2026.The Cloth contributors.
// 
// LlvmEmitter.cs is part of the Cloth Compiler.
// 
// Use, modification, and distribution of this file are governed by the
// license terms provided with the Cloth Compiler source distribution.

using System.Globalization;
using System.Text;
using Compiler.CIR;
using Compiler.Configs;
using Compiler.Semantics;

namespace Compiler.LLVM;

// Lowers a CirModule to LLVM IR text (.ll) and writes it to {projectRoot}/build/{ProjectName}.ll.
// Uses LLVM 15+ opaque-pointer style and the alloca/load/store pattern for all locals;
// `mem2reg` (run by clang) promotes them to SSA.
public sealed class LlvmEmitter {
	private readonly CirModule _module;
	private readonly ClothConfig _config;
	private readonly string _projectRoot;

	private readonly Dictionary<string, CirTypeDecl.Class> _classByFqn = new();
	// Enum FQN → CIR enum decl. Parallel to `_classByFqn`. Lets `EmitFieldGep` /
	// `LlvmTypeOf` resolve a field reference when the receiver is an enum singleton.
	private readonly Dictionary<string, CirTypeDecl.Enum> _enumByFqn = new();
	// classFqn → flattened field layout (root-to-leaf), with the vtable header only
	// contributed by the root. Lazily populated by GetFlattenedFields and used by both
	// struct-type emission and field-GEP indexing so a child instance can read/write
	// ancestor fields at their natural offsets.
	private readonly Dictionary<string, List<CirField>> _flattenedFields = new();
	private readonly HashSet<string> _definedFns = new();
	private readonly Dictionary<string, string> _externDecls = new();

	private readonly List<string> _strings = new();
	private readonly Dictionary<string, int> _stringIndex = new();

	// CirFunctions whose IsExtern == true. Keyed by MangledName (literal C symbol for @Extern,
	// or dotted CIR FQN for cross-project externs). Provides proper signatures for `declare` lines.
	private readonly Dictionary<string, CirFunction> _externFns = new();

	// CIR MangledName → final LLVM symbol. For @Extern (literal C symbol) the value matches the key;
	// for cross-project externs (dotted CIR FQN) the value is the LLVM-mangled form.
	private readonly Dictionary<string, string> _externLlvmName = new();

	// Set by `EmitPow` when at least one `^` operator emits an integer or float code path.
	// Drives the module-level helper / libm extern emission in `Build()`.
	private bool _needsIntPowHelper;
	private bool _needsLibmPow;

	// C-symbol → number of leading fixed parameters for variadic externs.
	// Populated when multiple @Extern declarations alias to the same C symbol with different
	// signatures (e.g. _printf_i32, _printf_i64 both → "printf"); the LLVM declare and call
	// syntax must use variadic form so each call site can pass its own argument types.
	private readonly Dictionary<string, int> _variadicLeading = new();

	// Per-function state
	private int _tempCounter;
	private string _currentThisFqn = "";
	private CirType _currentReturnType = new CirType.Void();
	private readonly List<string> _allocaLines = new();
	private readonly List<string> _prologueLines = new();
	private readonly List<string> _bodyLines = new();
	private bool _blockTerminated;
	private readonly Dictionary<string, string> _localAddrMap = new();
	private readonly Dictionary<string, CirType> _localTypeMap = new();

	// Stack of (continueLabel, breakLabel) per enclosing loop. `break;` jumps to the top
	// frame's break label; `continue;` to its continue label. Pushed at the start of a loop
	// body, popped at end. Empty outside any loop — break/continue outside a loop is a
	// hard error in LLVM (no terminator target), so the analyzer should reject those.
	private readonly Stack<(string Continue, string Break)> _loopStack = new();

	public LlvmEmitter(CirModule module, ClothConfig config, string projectRoot) {
		_module = module;
		_config = config;
		_projectRoot = projectRoot;

		foreach (var t in _module.Types) {
			if (t is CirTypeDecl.Class c)
				_classByFqn[c.FullyQualifiedName] = c;
			else if (t is CirTypeDecl.Enum e)
				_enumByFqn[e.FullyQualifiedName] = e;
		}
	}

	public string Emit() {
		var llText = Build();
		var buildDir = Path.Combine(_projectRoot, "build");
		Directory.CreateDirectory(buildDir);
		var llPath = Path.Combine(buildDir, _config.Project.Name + ".ll");
		File.WriteAllText(llPath, llText, new UTF8Encoding(false));
		return llPath;
	}

	// -------------------------------------------------------------------------
	// Module assembly
	// -------------------------------------------------------------------------

	private string Build() {
		PreScan();

		var sb = new StringBuilder();
		sb.AppendLine("; Generated by the Cloth Compiler");
		sb.AppendLine($"source_filename = \"{_config.Project.Name}\"");
		sb.AppendLine("target datalayout = \"e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128\"");
		sb.AppendLine($"target triple = \"{ResolveTriple(_config.Build.Target)}\"");
		sb.AppendLine();

		var types = EmitStructTypes();
		if (types.Length > 0) {
			sb.Append(types);
			sb.AppendLine();
		}

		var strs = EmitStringGlobals();
		if (strs.Length > 0) {
			sb.Append(strs);
			sb.AppendLine();
		}

		var externs = EmitExternDecls();
		if (externs.Length > 0) {
			sb.Append(externs);
			sb.AppendLine();
		}

		var vtables = EmitVtableGlobals();
		if (vtables.Length > 0) {
			sb.Append(vtables);
			sb.AppendLine();
		}

		var statics = EmitStaticFieldGlobals();
		if (statics.Length > 0) {
			sb.Append(statics);
			sb.AppendLine();
		}

		var enums = EmitEnumGlobals();
		if (enums.Length > 0) {
			sb.Append(enums);
			sb.AppendLine();
		}

		var enumFunctions = EmitEnumSyntheticFunctions();
		if (enumFunctions.Length > 0) {
			sb.Append(enumFunctions);
			sb.AppendLine();
		}

		foreach (var fn in _module.Functions) {
			if (fn.IsExtern) continue;
			// Compiler-synthesized enum helpers (e.g. `valueOf(string)`) have their LLVM
			// bodies emitted by `EmitEnumSyntheticFunctions` below, not through the normal
			// CIR-to-LLVM path. Skipping here avoids emitting a malformed empty define.
			if (fn.Kind == CirFunctionKind.EnumValueOf) continue;
			sb.Append(EmitFunction(fn));
			sb.AppendLine();
		}

		// Integer pow helper: lazy-emitted exponentiation-by-squaring (set in PreScan when
		// any `^` uses two integer operands). Float pow is declared as an extern up in
		// PreScan and routed to libm at the call site.
		if (_needsIntPowHelper) {
			sb.AppendLine(EmitIntPowHelper());
			sb.AppendLine();
		}

		if (_config.Build.OutputType == OutputType.Executable)
			sb.Append(EmitMainEntry());
		return sb.ToString();
	}

	// Exponentiation-by-squaring on i64. Returns 0 for non-positive exponents so the
	// integer path stays integer-typed; users wanting fractional results (e.g. `5 ^ -1`)
	// must cast the base to float first, routing through the libm path instead.
	private static string EmitIntPowHelper() => string.Join("\n", new[] {
		"define i64 @cloth_pow_i64(i64 %base, i64 %exp) {",
		"entry:",
		"  br label %loop",
		"loop:",
		"  %b = phi i64 [ %base, %entry ], [ %b_sq, %iter ]",
		"  %e = phi i64 [ %exp,  %entry ], [ %e_shr, %iter ]",
		"  %r = phi i64 [ 1,     %entry ], [ %r_next, %iter ]",
		"  %done = icmp sle i64 %e, 0",
		"  br i1 %done, label %exit, label %iter",
		"iter:",
		"  %odd = and i64 %e, 1",
		"  %is_odd = icmp ne i64 %odd, 0",
		"  %r_mul = mul i64 %r, %b",
		"  %r_next = select i1 %is_odd, i64 %r_mul, i64 %r",
		"  %b_sq = mul i64 %b, %b",
		"  %e_shr = ashr i64 %e, 1",
		"  br label %loop",
		"exit:",
		"  ret i64 %r",
		"}"
	});

	private static string ResolveTriple(string target) => target switch {
		"x64_86" or "x86_64" or "" => "x86_64-pc-windows-msvc",
		"x86" => "i686-pc-windows-msvc",
		"arm64" => "aarch64-pc-windows-msvc",
		_ => "x86_64-pc-windows-msvc"
	};

	// -------------------------------------------------------------------------
	// Pre-scan: collect defined functions, string literals, extern call targets
	// -------------------------------------------------------------------------

	private void PreScan() {
		// Group extern functions by C symbol to detect collisions (variadic candidates).
		var externsByName = new Dictionary<string, List<CirFunction>>();
		foreach (var fn in _module.Functions) {
			if (fn.IsExtern) {
				if (!externsByName.TryGetValue(fn.MangledName, out var list))
					externsByName[fn.MangledName] = list = new List<CirFunction>();
				list.Add(fn);
			}
			else {
				_definedFns.Add(fn.MangledName);
			}
		}

		foreach (var (cname, group) in externsByName) {
			var representative = group[0];
			_externFns[cname] = representative;
			// Dotted names are CIR FQNs (cross-project externs) and need LLVM mangling.
			// Names without dots are already final C symbols (from @Extern annotations).
			var llvmName = cname.Contains('.') ? MangleToLlvm(cname) : cname;
			_externLlvmName[cname] = llvmName;
			var retTy = LlvmType(representative.ReturnType);

			if (group.Count == 1) {
				var argSig = string.Join(", ", representative.Parameters.Select(p => LlvmType(p.Type)));
				_externDecls[cname] = $"declare {retTy} @{llvmName}({argSig})";
			}
			else {
				// Multiple @Extern declarations for the same C symbol — emit variadic.
				// Leading fixed parameters are the longest common prefix where all groups agree.
				var leading = LongestCommonParamPrefix(group);
				_variadicLeading[cname] = leading.Count;
				var leadSig = string.Join(", ", leading.Select(LlvmType));
				_externDecls[cname] = leading.Count == 0 ? $"declare {retTy} @{llvmName}(...)" : $"declare {retTy} @{llvmName}({leadSig}, ...)";
			}
		}

		foreach (var fn in _module.Functions) {
			foreach (var stmt in fn.Body)
				ScanStmt(stmt);
		}

		foreach (var t in _module.Types) {
			if (t is CirTypeDecl.Class c) {
				foreach (var f in c.Fields)
					if (f.Initializer != null)
						ScanExpr(f.Initializer);
			}
			// Pre-pool enum case-name strings (consumed by `getOrdinal()` / `name()` /
			// `EmitEnumGlobals`) and any string-literal constructor args so the strings
			// section emits a slot for them before the enum globals reference `@.str.N`.
			else if (t is CirTypeDecl.Enum enumDecl) {
				foreach (var ecase in enumDecl.Cases) {
					PoolStringIndex(ecase.Name);
					foreach (var arg in ecase.ConstructorArgs)
						ScanExpr(arg);
				}
			}
		}

		// libc allocators used by `new`/`delete` lowering. Always declared so the .ll links
		// regardless of whether the user code actually invokes either form.
		_externDecls["calloc"] = "declare ptr @calloc(i64, i64)";
		_externDecls["free"] = "declare void @free(ptr)";
		// Used by failed `as` downcasts to halt the program.
		_externDecls["abort"] = "declare void @abort()";
		// libm `pow` is only declared when `^` operates on at least one float operand
		// (`_needsLibmPow` set by the Pow scan above). Integer `^` uses the in-module
		// helper emitted by `EmitIntPowHelper`.
		if (_needsLibmPow) _externDecls["pow"] = "declare double @pow(double, double)";

		// libc `strcmp` is declared whenever the module defines at least one enum, since
		// the synthesized `valueOf(string)` for every enum uses it for string equality.
		if (_module.Types.Any(t => t is CirTypeDecl.Enum))
			_externDecls["strcmp"] = "declare i32 @strcmp(ptr, ptr)";
	}

	private void ScanStmt(CirStmt stmt) {
		switch (stmt) {
			case CirStmt.LocalDecl d:
				if (d.Init != null) ScanExpr(d.Init);
				break;
			case CirStmt.TupleDecl t:
				ScanExpr(t.Init);
				break;
			case CirStmt.Assign a:
				ScanExpr(a.Target);
				ScanExpr(a.Value);
				break;
			case CirStmt.Expr e: ScanExpr(e.Expression); break;
			case CirStmt.Discard d: ScanExpr(d.Expression); break;
			case CirStmt.Return r:
				if (r.Value != null) ScanExpr(r.Value);
				break;
			case CirStmt.If i:
				ScanExpr(i.Condition);
				foreach (var s in i.Then) ScanStmt(s);
				foreach (var (c, b) in i.ElseIfs) {
					ScanExpr(c);
					foreach (var s in b) ScanStmt(s);
				}

				if (i.Else != null)
					foreach (var s in i.Else)
						ScanStmt(s);
				break;
			case CirStmt.While w:
				ScanExpr(w.Condition);
				foreach (var s in w.Body) ScanStmt(s);
				break;
			case CirStmt.DoWhile dw:
				foreach (var s in dw.Body) ScanStmt(s);
				ScanExpr(dw.Condition);
				break;
			case CirStmt.For f:
				ScanStmt(f.Init);
				ScanExpr(f.Condition);
				ScanExpr(f.Iterator);
				foreach (var s in f.Body) ScanStmt(s);
				break;
			case CirStmt.ForIn fi:
				ScanExpr(fi.Iterable);
				foreach (var s in fi.Body) ScanStmt(s);
				break;
			case CirStmt.Switch sw:
				ScanExpr(sw.Subject);
				foreach (var c in sw.Cases) {
					if (c.Pattern != null) ScanExpr(c.Pattern);
					foreach (var s in c.Body) ScanStmt(s);
				}

				break;
			case CirStmt.Throw t: ScanExpr(t.Expression); break;
			case CirStmt.Delete d: ScanExpr(d.Expression); break;
			case CirStmt.Block b:
				foreach (var s in b.Body) ScanStmt(s);
				break;
		}
	}

	private void ScanExpr(CirExpr expr) {
		switch (expr) {
			case CirExpr.StrLit s:
				if (!_stringIndex.ContainsKey(s.Value)) {
					_stringIndex[s.Value] = _strings.Count;
					_strings.Add(s.Value);
				}

				break;
			case CirExpr.Binary b:
				// Detect Pow operands' widths now so the helper / libm extern lands in the
				// right module sections (externs are emitted before function bodies).
				if (b.Op == CirBinOp.Pow) {
					var lt = LlvmTypeOf(b.Left);
					var rt = LlvmTypeOf(b.Right);
					if (IsIntegerLlvmType(lt) && IsIntegerLlvmType(rt)) _needsIntPowHelper = true;
					else _needsLibmPow = true;
				}
				ScanExpr(b.Left);
				ScanExpr(b.Right);
				break;
			case CirExpr.Unary u: ScanExpr(u.Operand); break;
			case CirExpr.FieldAccess fa: ScanExpr(fa.Target); break;
			case CirExpr.Index i:
				ScanExpr(i.Target);
				ScanExpr(i.Idx);
				break;
			case CirExpr.Call c:
				if (!_definedFns.Contains(c.MangledName) && !_externFns.ContainsKey(c.MangledName))
					RecordExternCall(c.MangledName, c.Args.Count);
				foreach (var a in c.Args) ScanExpr(a);
				break;
			case CirExpr.IndirectCall ic:
				ScanExpr(ic.Callee);
				foreach (var a in ic.Args) ScanExpr(a);
				break;
			case CirExpr.VirtualCall vc:
				ScanExpr(vc.Receiver);
				foreach (var a in vc.Args) ScanExpr(a);
				break;
			case CirExpr.VtableRef:
				break;
			case CirExpr.Downcast dc:
				ScanExpr(dc.Receiver);
				break;
			case CirExpr.Alloc a:
				if (!_definedFns.Contains(a.CtorMangledName) && !_externFns.ContainsKey(a.CtorMangledName))
					RecordExternCall(a.CtorMangledName, a.Args.Count + 1);
				foreach (var x in a.Args) ScanExpr(x);
				break;
			case CirExpr.Cast c: ScanExpr(c.Value); break;
			case CirExpr.TypeCheck t: ScanExpr(t.Value); break;
			case CirExpr.Ternary t:
				ScanExpr(t.Condition);
				ScanExpr(t.Then);
				ScanExpr(t.Else);
				break;
			case CirExpr.NullCoalesce n:
				ScanExpr(n.Left);
				ScanExpr(n.Right);
				break;
			case CirExpr.TupleLit t:
				foreach (var e in t.Elements) ScanExpr(e);
				break;
			case CirExpr.Range r:
				ScanExpr(r.Start);
				ScanExpr(r.End);
				break;
		}
	}

	private static List<CirType> LongestCommonParamPrefix(List<CirFunction> fns) {
		var first = fns[0].Parameters;
		var common = new List<CirType>();
		for (var i = 0; i < first.Count; i++) {
			var ty = first[i].Type;
			if (fns.All(f => i < f.Parameters.Count && f.Parameters[i].Type == ty))
				common.Add(ty);
			else
				break;
		}

		return common;
	}

	private void RecordExternCall(string cirName, int argCount) {
		var llvmName = MangleToLlvm(cirName);
		if (_externDecls.ContainsKey(llvmName)) return;
		var args = string.Join(", ", Enumerable.Repeat("ptr", argCount));
		_externDecls[llvmName] = $"declare void @{llvmName}({args})";
	}

	// -------------------------------------------------------------------------
	// Sections
	// -------------------------------------------------------------------------

	private string EmitStructTypes() {
		var sb = new StringBuilder();
		foreach (var t in _module.Types) {
			if (t is CirTypeDecl.Class c) {
				var name = StructName(c.FullyQualifiedName);
				var flat = GetFlattenedFields(c.FullyQualifiedName);
				if (flat.Count == 0) {
					sb.AppendLine($"{name} = type {{ ptr }}");
					continue;
				}

				var fieldTypes = string.Join(", ", flat.Select(f => LlvmType(f.Type)));
				sb.AppendLine($"{name} = type {{ {fieldTypes} }}");
			}
			else if (t is CirTypeDecl.Enum e) {
				// `%enum.<fqn> = type { i32 ordinal, ptr name, <param-types...> }`. The two
				// leading slots are built-in (driven by `getOrdinal()` / `name()`); user
				// parameters follow in declaration order.
				var name = StructName(e.FullyQualifiedName);
				var fieldTypes = new List<string> { "i32", "ptr" };
				fieldTypes.AddRange(e.Parameters.Select(p => LlvmType(p.Type)));
				sb.AppendLine($"{name} = type {{ {string.Join(", ", fieldTypes)} }}");
			}
		}

		return sb.ToString();
	}

	private static string MangleEnumCaseGlobal(string enumFqn, string caseName) =>
		MangleToLlvm($"enum.{enumFqn}.{caseName}");

	// Emit one `@enum.<fqn>.<CASE> = constant ...` per case across all enums in the
	// module. Each case's user-supplied constructor args are folded to LLVM literal
	// constants via the static-field folder; the two built-in slots (ordinal, name) are
	// always literal. Extern enums get `external constant` declarations so the linker
	// resolves them against the dependency's `.lib`.
	private string EmitEnumGlobals() {
		var sb = new StringBuilder();
		foreach (var t in _module.Types) {
			if (t is not CirTypeDecl.Enum e) continue;
			var structTy = StructName(e.FullyQualifiedName);
			var isExtern = _enumExternFqns.Contains(e.FullyQualifiedName);

			foreach (var c in e.Cases) {
				var globalName = MangleEnumCaseGlobal(e.FullyQualifiedName, c.Name);
				if (isExtern) {
					sb.AppendLine($"@{globalName} = external constant {structTy}");
					continue;
				}

				// Built-in slots first: ordinal + name pointer. Pool the case-name string
				// literal through the existing string-globals path.
				var nameStrIdx = PoolStringIndex(c.Name);
				var initParts = new List<string> {
					$"i32 {c.Ordinal}",
					$"ptr @.str.{nameStrIdx}"
				};
				for (var i = 0; i < c.ConstructorArgs.Count; i++) {
					var paramTy = LlvmType(e.Parameters[i].Type);
					var folded = FoldStaticInitializer(c.ConstructorArgs[i]);
					if (folded != null) {
						initParts.Add($"{paramTy} {FormatLlvmConstant(folded.Value, paramTy)}");
						continue;
					}
					// String literals don't fold to a numeric value; pool them and emit a `ptr`.
					if (c.ConstructorArgs[i] is CirExpr.StrLit s) {
						var idx = PoolStringIndex(s.Value);
						initParts.Add($"ptr @.str.{idx}");
						continue;
					}
					LlvmError.UnsupportedExpression.WithMessage($"enum case '{e.FullyQualifiedName}.{c.Name}' arg {i} is not a compile-time constant").Render();
					return sb.ToString();
				}

				sb.AppendLine($"@{globalName} = constant {structTy} {{ {string.Join(", ", initParts)} }}");
			}
		}
		return sb.ToString();
	}

	// Add a string literal to the pool (if not already present) and return its index so
	// callers can reference `@.str.<idx>` as a constant. Distinct from `InternString`
	// (lower in the file) which emits a runtime GEP into the pool — this one only
	// produces a constant-init reference for global initializers.
	private int PoolStringIndex(string value) {
		if (_stringIndex.TryGetValue(value, out var existing)) return existing;
		var idx = _strings.Count;
		_stringIndex[value] = idx;
		_strings.Add(value);
		return idx;
	}

	// FQNs of enums defined in dependency projects. Populated in `Generate` when the
	// CirModule is constructed — for now, every enum in the module is local; cross-
	// project enum visibility is a follow-up.
	private readonly HashSet<string> _enumExternFqns = new();

	// Emit synthesized per-enum functions that don't go through the normal CIR pipeline.
	// Right now that's just `valueOf(string)` — chained `strcmp` against each case name,
	// returning the matching `@enum.<fqn>.<CASE>` pointer or null when no match. Skips
	// extern enums (their valueOf lives in the dependency).
	private string EmitEnumSyntheticFunctions() {
		var sb = new StringBuilder();
		foreach (var t in _module.Types) {
			if (t is not CirTypeDecl.Enum e) continue;
			if (_enumExternFqns.Contains(e.FullyQualifiedName)) continue;
			var mangled = MangleToLlvm($"{e.FullyQualifiedName}.valueOf__string");
			sb.AppendLine($"define ptr @{mangled}(ptr %name) {{");
			sb.AppendLine("entry:");
			if (e.Cases.Count == 0) {
				// Vacuous case — empty enum (unreachable today, defensive). Return null.
				sb.AppendLine("  ret ptr null");
				sb.AppendLine("}");
				continue;
			}
			sb.AppendLine($"  br label %check0");
			for (var i = 0; i < e.Cases.Count; i++) {
				var c = e.Cases[i];
				var nameStrIdx = PoolStringIndex(c.Name);
				var nextLabel = i + 1 < e.Cases.Count ? $"check{i + 1}" : "miss";
				sb.AppendLine($"check{i}:");
				sb.AppendLine($"  %cmp{i} = call i32 @strcmp(ptr %name, ptr @.str.{nameStrIdx})");
				sb.AppendLine($"  %eq{i} = icmp eq i32 %cmp{i}, 0");
				sb.AppendLine($"  br i1 %eq{i}, label %match{i}, label %{nextLabel}");
				sb.AppendLine($"match{i}:");
				sb.AppendLine($"  ret ptr @{MangleEnumCaseGlobal(e.FullyQualifiedName, c.Name)}");
			}
			sb.AppendLine("miss:");
			sb.AppendLine("  ret ptr null");
			sb.AppendLine("}");
		}
		return sb.ToString();
	}

	// Map an enum field name (built-in `__ordinal__` / `__name__`, or a declared
	// parameter) to its `{ tag, name, params... }` struct index and the corresponding
	// CIR type. Returns (-1, undef) when the name doesn't match anything.
	private static (int index, CirType type) ResolveEnumFieldIndex(CirTypeDecl.Enum e, string fieldName) {
		if (fieldName == "__ordinal__") return (0, new CirType.Named("i32"));
		if (fieldName == "__name__") return (1, new CirType.Named("string"));
		for (var i = 0; i < e.Parameters.Count; i++)
			if (e.Parameters[i].Name == fieldName) return (i + 2, e.Parameters[i].Type);
		return (-1, new CirType.Any());
	}

	// Build the flattened layout for `classFqn`: root's fields first (including the vtable
	// header), then each descendant's contributions in chain order with the duplicate
	// vtable field skipped. This preserves the invariant that an ancestor pointer cast to
	// a descendant pointer sees the same offsets for shared fields. A defensive visited-
	// set guards against malformed BaseClass rings (the registry-level cycle detector
	// already prevents these in normal compiles, but LLVM can't see the registry).
	private List<CirField> GetFlattenedFields(string classFqn) {
		if (_flattenedFields.TryGetValue(classFqn, out var cached)) return cached;

		var chain = new List<string>();
		var visited = new HashSet<string>();
		var cursor = classFqn;
		while (!string.IsNullOrEmpty(cursor) && _classByFqn.TryGetValue(cursor, out var cls)) {
			if (!visited.Add(cursor)) break;
			chain.Insert(0, cursor);
			cursor = cls.BaseClass;
		}

		var result = new List<CirField>();
		for (var i = 0; i < chain.Count; i++) {
			var cls = _classByFqn[chain[i]];
			if (i == 0) {
				result.AddRange(cls.Fields);
			}
			else {
				// Skip the descendant's `__vtable__` field — the root already contributed one
				// at offset 0, and `this.__vtable__ = &__vtable_<Self>` simply overwrites
				// that slot at construction time for each level of the chain.
				result.AddRange(cls.Fields.Where(f => f.Name != SymbolRegistry.VtableFieldName));
			}
		}

		_flattenedFields[classFqn] = result;
		return result;
	}

	private string EmitStringGlobals() {
		var sb = new StringBuilder();
		for (var i = 0; i < _strings.Count; i++) {
			var (encoded, byteCount) = EncodeStringConstant(_strings[i]);
			sb.AppendLine($"@.str.{i} = private unnamed_addr constant [{byteCount} x i8] c\"{encoded}\", align 1");
		}

		return sb.ToString();
	}

	private string EmitExternDecls() {
		var sb = new StringBuilder();
		foreach (var line in _externDecls.Values)
			sb.AppendLine(line);
		return sb.ToString();
	}

	// One global per class with `IsList` non-empty. Each global is a constant array of
	// function pointers, sized to the program-wide VtableSize. Slots that the class doesn't
	// implement contain `null`; populated slots reference the implementing function (either
	// a class-side override or an interface's default-impl symbol). Function symbols are
	// LLVM-mangled at reference time, matching how function definitions are emitted.
	private string EmitVtableGlobals() {
		var sb = new StringBuilder();
		foreach (var vt in _module.Vtables) {
			var size = vt.Slots.Count;
			var globalName = MangleVtableGlobal(vt.ClassFqn);
			var structTy = $"{{ ptr, [{size} x ptr] }}";

			// Extern vtables (classes defined in a dependency project) are declared, not
			// defined — the linker resolves them against the dependency's `.lib`. Emitting
			// a definition here would produce `LNK2005: multiply defined symbol` at link time.
			if (vt.IsExtern) {
				sb.AppendLine($"@{globalName} = external constant {structTy}");
				continue;
			}

			var parentRef = vt.ParentClassFqn == null ? "ptr null" : $"ptr @{MangleVtableGlobal(vt.ParentClassFqn)}";
			if (size == 0) {
				sb.AppendLine($"@{globalName} = constant {structTy} {{ {parentRef}, [0 x ptr] zeroinitializer }}");
				continue;
			}

			var entries = vt.Slots.Select(slot => slot == null ? "ptr null" : $"ptr @{MangleToLlvm(slot)}");
			sb.AppendLine($"@{globalName} = constant {structTy} {{ {parentRef}, [{size} x ptr] [{string.Join(", ", entries)}] }}");
		}

		return sb.ToString();
	}

	// Vtable size constant — number of interface-method slots in every class's vtable
	// (uniform across the program). Stored on `_module` indirectly through `CirVtable.Slots`,
	// but easier to read here for GEPs that need the array length.
	private int VtableSlotCount() => _module.Vtables.Count > 0 ? _module.Vtables[0].Slots.Count : 0;

	// LLVM-safe symbol for a class's vtable global. Reuses MangleToLlvm so dotted FQNs
	// produce valid IR identifiers (e.g. `__vtable_hello_world_Speaker`).
	private static string MangleVtableGlobal(string classFqn) =>
		MangleToLlvm($"__vtable_{classFqn}");

	// LLVM-safe symbol for a class-level static or const field: `cloth_math_Math_PI`.
	// Same encoding as method names so cross-project linking sees a stable name.
	private static string MangleStaticGlobal(string classFqn, string fieldName) =>
		MangleToLlvm($"{classFqn}.{fieldName}");

	// Folded values for already-emitted static fields, keyed by `{ClassFqn}.{Name}`. The
	// initializer for one static can reference another via a `StaticFieldRef`; we look it
	// up here during emission so the initializer compiles to a literal LLVM constant.
	private readonly Dictionary<string, double> _foldedStatics = new();

	// Emit one `@<mangled>` LLVM global per static / class-level-const field. Local fields
	// get a constant or global initializer (folded at compile time); extern fields (from
	// dependency projects) get an `external` declaration so the linker resolves them
	// against the dependency's `.lib`.
	private string EmitStaticFieldGlobals() {
		var sb = new StringBuilder();
		foreach (var sf in _module.StaticFields) {
			var globalName = MangleStaticGlobal(sf.ClassFqn, sf.Name);
			var llvmTy = LlvmType(sf.Type);
			var linkage = sf.IsConst ? "constant" : "global";

			if (sf.IsExtern) {
				sb.AppendLine($"@{globalName} = external {linkage} {llvmTy}");
				continue;
			}

			if (sf.Initializer == null) {
				sb.AppendLine($"@{globalName} = {linkage} {llvmTy} zeroinitializer");
				continue;
			}

			var folded = FoldStaticInitializer(sf.Initializer);
			if (folded == null) {
				LlvmError.UnsupportedExpression.WithMessage($"initializer for static field '{sf.ClassFqn}.{sf.Name}' is not a compile-time constant").Render();
				return sb.ToString();
			}

			_foldedStatics[$"{sf.ClassFqn}.{sf.Name}"] = folded.Value;
			sb.AppendLine($"@{globalName} = {linkage} {llvmTy} {FormatLlvmConstant(folded.Value, llvmTy)}");
		}

		return sb.ToString();
	}

	// Fold a CIR expression to a numeric constant at compile time. Supports integer/float
	// literals, unary `-`, binary arithmetic over folded operands, and references to other
	// static fields whose values are already in `_foldedStatics`. Returns null when the
	// expression isn't constant-foldable.
	private double? FoldStaticInitializer(CirExpr e) {
		switch (e) {
			case CirExpr.IntLit i:
				return double.TryParse(i.Value, System.Globalization.NumberStyles.Integer | System.Globalization.NumberStyles.AllowLeadingSign, System.Globalization.CultureInfo.InvariantCulture, out var iv) ? iv : null;
			case CirExpr.FloatLit f:
				return double.TryParse(f.Value, System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out var fv) ? fv : null;
			case CirExpr.BoolLit b:
				return b.Value ? 1.0 : 0.0;
			case CirExpr.StaticFieldRef sr:
				return _foldedStatics.TryGetValue($"{sr.ClassFqn}.{sr.Name}", out var v) ? v : null;
			case CirExpr.Unary u:
				var operand = FoldStaticInitializer(u.Operand);
				if (operand == null) return null;
				return u.Op switch {
					CirUnOp.Neg => -operand,
					_ => null
				};
			case CirExpr.Binary b:
				var l = FoldStaticInitializer(b.Left);
				var r = FoldStaticInitializer(b.Right);
				if (l == null || r == null) return null;
				return b.Op switch {
					CirBinOp.Add => l + r,
					CirBinOp.Sub => l - r,
					CirBinOp.Mul => l * r,
					CirBinOp.Div => r != 0 ? l / r : null,
					CirBinOp.Rem => r != 0 ? l % r : null,
					CirBinOp.Pow => Math.Pow(l.Value, r.Value),
					_ => null
				};
			case CirExpr.Cast c:
				return FoldStaticInitializer(c.Value);
		}
		return null;
	}

	// Format a folded numeric value as an LLVM constant matching the target type.
	// Floats use IEEE-754 hex form. LLVM requires `float`-typed hex constants to round-
	// trip exactly through IEEE-754 double (per LangRef), so for `float` we cast the
	// value to single precision before encoding — that produces a double value with
	// only the low bits that survive the round-trip.
	private static string FormatLlvmConstant(double value, string llvmTy) {
		if (llvmTy == "float") {
			var asFloat = (float) value;
			var bits = BitConverter.DoubleToInt64Bits(asFloat);
			return "0x" + bits.ToString("X16");
		}
		if (llvmTy == "double") {
			var bits = BitConverter.DoubleToInt64Bits(value);
			return "0x" + bits.ToString("X16");
		}
		return ((long) value).ToString(System.Globalization.CultureInfo.InvariantCulture);
	}

	// -------------------------------------------------------------------------
	// Functions
	// -------------------------------------------------------------------------

	private string EmitFunction(CirFunction fn) {
		_tempCounter = 0;
		_currentThisFqn = "";
		_currentReturnType = fn.ReturnType;
		_allocaLines.Clear();
		_prologueLines.Clear();
		_bodyLines.Clear();
		_blockTerminated = false;
		_localAddrMap.Clear();
		_localTypeMap.Clear();
		_loopStack.Clear();

		var llvmName = MangleToLlvm(fn.MangledName);
		var paramSigParts = new List<string>();
		foreach (var p in fn.Parameters) {
			var ty = LlvmType(p.Type);
			paramSigParts.Add($"{ty} %{p.Name}");

			var addr = $"%{p.Name}.addr";
			_allocaLines.Add($"  {addr} = alloca {ty}, align 8");
			_prologueLines.Add($"  store {ty} %{p.Name}, ptr {addr}");
			_localAddrMap[p.Name] = addr;
			_localTypeMap[p.Name] = p.Type;

			if (p.Name == "this" && p.Type is CirType.Ptr ptr && ptr.Inner is CirType.Named named)
				_currentThisFqn = named.FullyQualifiedName;
		}

		var retTy = LlvmType(fn.ReturnType);
		var paramSig = string.Join(", ", paramSigParts);

		foreach (var stmt in fn.Body)
			EmitStmt(stmt);

		if (!_blockTerminated) {
			_bodyLines.Add(fn.ReturnType is CirType.Void ? "  ret void" : $"  ret {retTy} {DefaultValue(fn.ReturnType)}");
		}

		var sb = new StringBuilder();
		sb.AppendLine($"define {retTy} @{llvmName}({paramSig}) {{");
		sb.AppendLine("entry:");
		foreach (var line in _allocaLines) sb.AppendLine(line);
		foreach (var line in _prologueLines) sb.AppendLine(line);
		foreach (var line in _bodyLines) sb.AppendLine(line);
		sb.AppendLine("}");
		return sb.ToString();
	}

	private string EmitMainEntry() {
		var mainCtor = FindMainCtor();
		if (mainCtor == null) {
			if (_config.Build.OutputType == OutputType.Executable)
				LlvmError.NoEntryPoint.WithMessage($"project '{_config.Project.Name}' has output=executable but no class defines a constructor accepting 'args'").Render();
			return "";
		}

		var thisParam = mainCtor.Parameters[0];
		var thisFqn = ((CirType.Named)((CirType.Ptr)thisParam.Type).Inner).FullyQualifiedName;
		var structName = StructName(thisFqn);
		var ctorLlvm = MangleToLlvm(mainCtor.MangledName);

		// Find a matching destructor (mangled name ends with .~ClassName)
		var className = thisFqn.Contains('.') ? thisFqn[(thisFqn.LastIndexOf('.') + 1)..] : thisFqn;
		var dtorCir = $"{thisFqn}.~{className}";
		var dtorLlvm = _definedFns.Contains(dtorCir) ? MangleToLlvm(dtorCir) : null;

		var sb = new StringBuilder();
		sb.AppendLine("define i32 @main(i32 %argc, ptr %argv) {");
		sb.AppendLine("entry:");
		sb.AppendLine($"  %instance = alloca {structName}, align 8");
		// Match the heap-allocation path's zero-init guarantee for stack-allocated Main, so
		// fields without explicit initializers come up as 0/null/false even at the entry point.
		sb.AppendLine($"  store {structName} zeroinitializer, ptr %instance, align 8");
		// Pass argv as the 'args' parameter (opaque ptr — runtime conversion is a future concern).
		sb.AppendLine($"  call void @{ctorLlvm}(ptr %instance, ptr %argv)");
		if (dtorLlvm != null)
			sb.AppendLine($"  call void @{dtorLlvm}(ptr %instance)");
		sb.AppendLine("  ret i32 0");
		sb.AppendLine("}");
		return sb.ToString();
	}

	private CirFunction? FindMainCtor() {
		// Pick the first constructor whose explicit parameters include 'args'.
		foreach (var fn in _module.Functions) {
			if (fn.Kind != CirFunctionKind.Constructor) continue;
			// Parameters[0] is always 'this'; look for another named 'args'.
			for (var i = 1; i < fn.Parameters.Count; i++)
				if (fn.Parameters[i].Name == "args")
					return fn;
		}

		return null;
	}

	// -------------------------------------------------------------------------
	// Statements
	// -------------------------------------------------------------------------

	private void EmitStmt(CirStmt stmt) {
		switch (stmt) {
			case CirStmt.LocalDecl d: EmitLocalDecl(d); break;
			case CirStmt.Assign a: EmitAssign(a); break;
			case CirStmt.Expr e: EmitExprStmt(e.Expression); break;
			case CirStmt.Discard d: EmitExprStmt(d.Expression); break;
			case CirStmt.Return r: EmitReturn(r); break;
			case CirStmt.If i: EmitIf(i); break;
			case CirStmt.While w: EmitWhile(w); break;
			case CirStmt.DoWhile dw: EmitDoWhile(dw); break;
			case CirStmt.For f: EmitFor(f); break;
			case CirStmt.Break: EmitBreak(); break;
			case CirStmt.Continue: EmitContinue(); break;
			case CirStmt.Delete del: EmitDelete(del); break;
			case CirStmt.Switch sw: EmitSwitch(sw); break;
			case CirStmt.Block b:
				foreach (var s in b.Body) EmitStmt(s);
				break;
			default:
				LlvmError.UnsupportedStatement.WithMessage($"{stmt.GetType().Name} is not yet lowerable to LLVM IR").Render();
				break;
		}
	}

	// `delete obj;` — call the destructor (if defined for the target's class) and free the
	// heap allocation. Pairs with EmitAlloc's calloc.
	private void EmitDelete(CirStmt.Delete d) {
		var ptr = EmitExpr(d.Expression);
		if (!string.IsNullOrEmpty(d.ClassFqn) && _classByFqn.ContainsKey(d.ClassFqn)) {
			// MangleDtor convention: `<TypeFqn>.~<ClassName>`.
			var className = d.ClassFqn.Contains('.') ? d.ClassFqn[(d.ClassFqn.LastIndexOf('.') + 1)..] : d.ClassFqn;
			var dtorCir = $"{d.ClassFqn}.~{className}";
			if (_definedFns.Contains(dtorCir)) {
				var dtorLlvm = MangleToLlvm(dtorCir);
				_bodyLines.Add($"  call void @{dtorLlvm}(ptr {ptr})");
			}
		}

		_bodyLines.Add($"  call void @free(ptr {ptr})");
	}

	private void EmitIf(CirStmt.If i) {
		var endLabel = FreshLabel("if_end");
		EmitIfBranches(i.Condition, i.Then, i.ElseIfs, 0, i.Else, endLabel);
		_bodyLines.Add($"{endLabel}:");
		_blockTerminated = false;
	}

	private void EmitIfBranches(CirExpr cond, List<CirStmt> thenBody, List<(CirExpr Cond, List<CirStmt> Body)> elseIfs, int idx, List<CirStmt>? elseBody, string endLabel) {
		var thenLabel = FreshLabel("then");
		var elseLabel = FreshLabel("else");
		var c = EmitExpr(cond);
		_bodyLines.Add($"  br i1 {c}, label %{thenLabel}, label %{elseLabel}");

		_bodyLines.Add($"{thenLabel}:");
		_blockTerminated = false;
		foreach (var s in thenBody) EmitStmt(s);
		if (!_blockTerminated) _bodyLines.Add($"  br label %{endLabel}");

		_bodyLines.Add($"{elseLabel}:");
		_blockTerminated = false;
		if (idx < elseIfs.Count) {
			var (nextCond, nextBody) = elseIfs[idx];
			EmitIfBranches(nextCond, nextBody, elseIfs, idx + 1, elseBody, endLabel);
		}
		else if (elseBody != null) {
			foreach (var s in elseBody) EmitStmt(s);
			if (!_blockTerminated) _bodyLines.Add($"  br label %{endLabel}");
		}
		else {
			_bodyLines.Add($"  br label %{endLabel}");
		}
	}

	// `switch (subject) { case pattern: body; default: body; }` — break-by-default per
	// case (no C-style fall-through). Lowers as a chain of `icmp eq` comparisons against
	// each case's pattern value. Floating-point subjects use `fcmp oeq`. Enum-typed
	// subjects compare as pointers (each variant is a singleton global). A `default:`
	// arm is the miss target; without one, the miss path falls through to switch-end.
	// `break` inside a case body jumps to switch-end via the loop-stack.
	private void EmitSwitch(CirStmt.Switch sw) {
		var subjectVal = EmitExpr(sw.Subject);
		var subjectTy = LlvmTypeOf(sw.Subject);
		var cmpOp = subjectTy is "float" or "double" ? "fcmp oeq" : "icmp eq";
		var endLabel = FreshLabel("switch_end");

		// Split pattern arms from the (at most one) default arm and pre-allocate every
		// label so the emission is linear and self-referential branches are simple.
		var patternIdx = new List<int>();          // indices into sw.Cases for pattern arms
		var defaultIdx = -1;
		for (var i = 0; i < sw.Cases.Count; i++) {
			if (sw.Cases[i].Pattern == null) defaultIdx = i;
			else patternIdx.Add(i);
		}

		var bodyLabels = new string[sw.Cases.Count];
		for (var i = 0; i < sw.Cases.Count; i++)
			bodyLabels[i] = FreshLabel(sw.Cases[i].Pattern == null ? "case_default" : "case_body");

		var missLabel = defaultIdx >= 0 ? bodyLabels[defaultIdx] : endLabel;

		// Per-pattern check labels (each block runs one compare + branch). The first one
		// is what entry falls into; each subsequent check is the failure target of the
		// previous one.
		var checkLabels = patternIdx.Select(_ => FreshLabel("check")).ToList();

		// Entry: branch into the first check (or directly to the miss target if there
		// are no pattern arms).
		if (checkLabels.Count > 0) _bodyLines.Add($"  br label %{checkLabels[0]}");
		else _bodyLines.Add($"  br label %{missLabel}");

		// Emit one `check<i>: cmp; br` block per pattern arm.
		for (var k = 0; k < patternIdx.Count; k++) {
			_bodyLines.Add($"{checkLabels[k]}:");
			_blockTerminated = false;
			var caseIdx = patternIdx[k];
			var pat = EmitExpr(sw.Cases[caseIdx].Pattern!);
			var cmp = FreshTemp();
			_bodyLines.Add($"  {cmp} = {cmpOp} {subjectTy} {subjectVal}, {pat}");
			var nextLabel = k + 1 < checkLabels.Count ? checkLabels[k + 1] : missLabel;
			_bodyLines.Add($"  br i1 {cmp}, label %{bodyLabels[caseIdx]}, label %{nextLabel}");
		}

		// Emit each case body — pattern arms in declaration order, then the default arm
		// (if any). `break` inside a body resolves through the loop-stack to switch-end.
		_loopStack.Push((endLabel, endLabel));
		for (var i = 0; i < sw.Cases.Count; i++) {
			_bodyLines.Add($"{bodyLabels[i]}:");
			_blockTerminated = false;
			foreach (var s in sw.Cases[i].Body) EmitStmt(s);
			if (!_blockTerminated) _bodyLines.Add($"  br label %{endLabel}");
		}
		_loopStack.Pop();

		_bodyLines.Add($"{endLabel}:");
		_blockTerminated = false;
	}

	// `while (cond) { body }`. `continue` jumps to the condition block; `break` to the end.
	private void EmitWhile(CirStmt.While w) {
		var condLabel = FreshLabel("while_cond");
		var bodyLabel = FreshLabel("while_body");
		var endLabel = FreshLabel("while_end");

		_bodyLines.Add($"  br label %{condLabel}");
		_bodyLines.Add($"{condLabel}:");
		_blockTerminated = false;
		var c = EmitExpr(w.Condition);
		_bodyLines.Add($"  br i1 {c}, label %{bodyLabel}, label %{endLabel}");

		_bodyLines.Add($"{bodyLabel}:");
		_blockTerminated = false;
		_loopStack.Push((condLabel, endLabel));
		foreach (var s in w.Body) EmitStmt(s);
		_loopStack.Pop();
		if (!_blockTerminated) _bodyLines.Add($"  br label %{condLabel}");

		_bodyLines.Add($"{endLabel}:");
		_blockTerminated = false;
	}

	// `do { body } while (cond);`. The body runs first; `continue` then evaluates `cond`,
	// `break` exits the loop. Re-enters the body when `cond` is true.
	private void EmitDoWhile(CirStmt.DoWhile dw) {
		var bodyLabel = FreshLabel("do_body");
		var condLabel = FreshLabel("do_cond");
		var endLabel = FreshLabel("do_end");

		_bodyLines.Add($"  br label %{bodyLabel}");
		_bodyLines.Add($"{bodyLabel}:");
		_blockTerminated = false;
		_loopStack.Push((condLabel, endLabel));
		foreach (var s in dw.Body) EmitStmt(s);
		_loopStack.Pop();
		if (!_blockTerminated) _bodyLines.Add($"  br label %{condLabel}");

		_bodyLines.Add($"{condLabel}:");
		_blockTerminated = false;
		var c = EmitExpr(dw.Condition);
		_bodyLines.Add($"  br i1 {c}, label %{bodyLabel}, label %{endLabel}");

		_bodyLines.Add($"{endLabel}:");
		_blockTerminated = false;
	}

	// `for (init; cond; iter) { body }`. C-style three-part loop. `continue` jumps to the
	// iter block (so the post-increment runs), then re-checks cond; `break` exits.
	private void EmitFor(CirStmt.For f) {
		EmitStmt(f.Init);
		var condLabel = FreshLabel("for_cond");
		var bodyLabel = FreshLabel("for_body");
		var iterLabel = FreshLabel("for_iter");
		var endLabel = FreshLabel("for_end");

		_bodyLines.Add($"  br label %{condLabel}");
		_bodyLines.Add($"{condLabel}:");
		_blockTerminated = false;
		var c = EmitExpr(f.Condition);
		_bodyLines.Add($"  br i1 {c}, label %{bodyLabel}, label %{endLabel}");

		_bodyLines.Add($"{bodyLabel}:");
		_blockTerminated = false;
		_loopStack.Push((iterLabel, endLabel));
		foreach (var s in f.Body) EmitStmt(s);
		_loopStack.Pop();
		if (!_blockTerminated) _bodyLines.Add($"  br label %{iterLabel}");

		_bodyLines.Add($"{iterLabel}:");
		_blockTerminated = false;
		_ = EmitExpr(f.Iterator);
		_bodyLines.Add($"  br label %{condLabel}");

		_bodyLines.Add($"{endLabel}:");
		_blockTerminated = false;
	}

	private void EmitBreak() {
		if (_loopStack.Count == 0) {
			LlvmError.UnsupportedStatement.WithMessage("'break' outside of any loop").Render();
			return;
		}
		_bodyLines.Add($"  br label %{_loopStack.Peek().Break}");
		_blockTerminated = true;
	}

	private void EmitContinue() {
		if (_loopStack.Count == 0) {
			LlvmError.UnsupportedStatement.WithMessage("'continue' outside of any loop").Render();
			return;
		}
		_bodyLines.Add($"  br label %{_loopStack.Peek().Continue}");
		_blockTerminated = true;
	}

	private string FreshLabel(string prefix) => $"{prefix}_{_tempCounter++}";

	private void EmitLocalDecl(CirStmt.LocalDecl d) {
		var ty = d.Type ?? new CirType.Any();
		var llvmTy = LlvmType(ty);
		var addr = $"%{d.Name}.addr";
		_allocaLines.Add($"  {addr} = alloca {llvmTy}, align 8");
		_localAddrMap[d.Name] = addr;
		_localTypeMap[d.Name] = ty;

		if (d.Init != null) {
			var val = EmitExpr(d.Init);
			_bodyLines.Add($"  store {llvmTy} {val}, ptr {addr}");
		}
	}

	private void EmitAssign(CirStmt.Assign a) {
		var addr = EmitAddrOf(a.Target);
		var (targetTy, _) = TypeOfLvalue(a.Target);
		var llvmTy = LlvmType(targetTy);
		var rhs = EmitExpr(a.Value);

		if (a.Op == CirAssignOp.Assign) {
			_bodyLines.Add($"  store {llvmTy} {rhs} , ptr {addr}".Replace(" , ", ", "));
		}
		else {
			var loaded = FreshTemp();
			_bodyLines.Add($"  {loaded} = load {llvmTy}, ptr {addr}");
			var op = AssignToBinOp(a.Op);
			var combined = FreshTemp();
			_bodyLines.Add($"  {combined} = {LlvmBinOp(op, llvmTy)} {llvmTy} {loaded}, {rhs}");
			_bodyLines.Add($"  store {llvmTy} {combined}, ptr {addr}");
		}
	}

	private void EmitExprStmt(CirExpr expr) {
		// Calls and other side-effecting expressions; emit and discard.
		_ = EmitExpr(expr);
	}

	private void EmitReturn(CirStmt.Return r) {
		if (r.Value == null) {
			_bodyLines.Add("  ret void");
		}
		else {
			var val = EmitExpr(r.Value);
			_bodyLines.Add($"  ret {LlvmType(_currentReturnType)} {val}");
		}

		_blockTerminated = true;
	}

	// -------------------------------------------------------------------------
	// Expressions
	// -------------------------------------------------------------------------

	// Returns the SSA name (e.g. "%_t3") or literal (e.g. "42") representing the value.
	private string EmitExpr(CirExpr expr) {
		switch (expr) {
			case CirExpr.IntLit i: return i.Value;
			case CirExpr.FloatLit f: return f.Value;
			case CirExpr.BoolLit b: return b.Value ? "1" : "0";
			case CirExpr.CharLit c: return ((int)c.Value).ToString(CultureInfo.InvariantCulture);
			case CirExpr.StrLit s: return InternString(s.Value);
			case CirExpr.NullLit: return "null";

			case CirExpr.Local l: return EmitLocalLoad(l.Name);
			case CirExpr.ThisPtr: return EmitLocalLoad("this");

			case CirExpr.FieldAccess fa: return EmitFieldLoad(fa);
			case CirExpr.StaticFieldRef sr: return EmitStaticFieldLoad(sr);
			case CirExpr.EnumCaseRef ec: return "@" + MangleEnumCaseGlobal(ec.EnumFqn, ec.CaseName);
			case CirExpr.Call c: return EmitCall(c);
			case CirExpr.Alloc a: return EmitAlloc(a);
			case CirExpr.VtableRef v: return $"@{MangleVtableGlobal(v.ClassFqn)}";
			case CirExpr.VirtualCall vc: return EmitVirtualCall(vc);
			case CirExpr.NullCoalesce nc: return EmitNullCoalesce(nc);
			case CirExpr.Downcast dc: return EmitDowncast(dc);
			case CirExpr.TypeCheck tc: return EmitTypeCheck(tc);

			case CirExpr.Binary b: return EmitBinary(b);
			case CirExpr.Unary u: return EmitUnary(u);
			case CirExpr.Cast cast: return EmitCast(cast);
		}

		LlvmError.UnsupportedExpression.WithMessage($"{expr.GetType().Name} is not yet lowerable to LLVM IR").Render();
		return "undef";
	}

	private string EmitLocalLoad(string name) {
		if (!_localAddrMap.TryGetValue(name, out var addr) || !_localTypeMap.TryGetValue(name, out var ty)) {
			LlvmError.UnsupportedExpression.WithMessage($"reference to unknown local '{name}'").Render();
			return "undef";
		}

		var t = FreshTemp();
		_bodyLines.Add($"  {t} = load {LlvmType(ty)}, ptr {addr}");
		return t;
	}

	private string EmitFieldLoad(CirExpr.FieldAccess fa) {
		var (gep, fieldType) = EmitFieldGep(fa);
		var t = FreshTemp();
		_bodyLines.Add($"  {t} = load {LlvmType(fieldType)}, ptr {gep}");
		return t;
	}

	// Load a class-level static / const field by emitting a `load` from the corresponding
	// LLVM global. The global's symbol is `@<mangled-class>_<field>` (matching
	// `EmitStaticFieldGlobals` and the cross-project `external` declaration shape).
	private string EmitStaticFieldLoad(CirExpr.StaticFieldRef sr) {
		var globalName = MangleStaticGlobal(sr.ClassFqn, sr.Name);
		var llvmTy = LlvmType(sr.Type);
		var t = FreshTemp();
		_bodyLines.Add($"  {t} = load {llvmTy}, ptr @{globalName}");
		return t;
	}

	private (string gep, CirType fieldType) EmitFieldGep(CirExpr.FieldAccess fa) {
		var targetVal = EmitExpr(fa.Target);
		var fqn = ResolveTargetFqn(fa.Target);
		if (fqn == null) {
			LlvmError.FieldNotFound.WithMessage($"cannot resolve owning type of field '{fa.FieldName}'").Render();
			return ("undef", new CirType.Any());
		}

		// Enum field layout: { i32 ordinal, ptr name, <params...> }. The two built-in
		// slots are referenced by the synthesized `getOrdinal()` and `name()` getters
		// using their `__ordinal__` / `__name__` reserved field names.
		if (_enumByFqn.TryGetValue(fqn, out var enumDecl)) {
			var (idx, fieldTy) = ResolveEnumFieldIndex(enumDecl, fa.FieldName);
			if (idx < 0) {
				LlvmError.FieldNotFound.WithMessage($"field '{fa.FieldName}' not found on enum {fqn}").Render();
				return ("undef", new CirType.Any());
			}
			var gep = FreshTemp();
			_bodyLines.Add($"  {gep} = getelementptr inbounds {StructName(fqn)}, ptr {targetVal}, i32 0, i32 {idx}");
			return (gep, fieldTy);
		}

		if (!_classByFqn.ContainsKey(fqn)) {
			LlvmError.FieldNotFound.WithMessage($"cannot resolve owning type of field '{fa.FieldName}'").Render();
			return ("undef", new CirType.Any());
		}

		// Look up the field in the flattened layout (own fields + ancestor contributions)
		// so an ancestor-declared field GEPs to its correct offset in the child's struct.
		var flat = GetFlattenedFields(fqn);
		var idx2 = flat.FindIndex(f => f.Name == fa.FieldName);
		if (idx2 < 0) {
			LlvmError.FieldNotFound.WithMessage($"field '{fa.FieldName}' not found on {fqn}").Render();
			return ("undef", new CirType.Any());
		}

		var gep2 = FreshTemp();
		_bodyLines.Add($"  {gep2} = getelementptr inbounds {StructName(fqn)}, ptr {targetVal}, i32 0, i32 {idx2}");
		return (gep2, flat[idx2].Type);
	}

	private string EmitCall(CirExpr.Call c) {
		// For known externs, use the pre-computed LLVM symbol (literal C name for @Extern,
		// LLVM-mangled form for cross-project externs). For other targets, mangle on the spot.
		var llvmName = _externLlvmName.TryGetValue(c.MangledName, out var ext) ? ext : MangleToLlvm(c.MangledName);
		var isVariadic = _variadicLeading.ContainsKey(c.MangledName);

		// Variadic externs: type each arg from the expression itself (locals via _localTypeMap,
		// literals from their CIR variant). Avoids the "first registered signature wins" bug.
		// Non-variadic: keep the existing behavior — types come from the registered function's signature.
		List<string> argTypes;
		if (isVariadic) {
			argTypes = c.Args.Select(LlvmTypeOf).ToList();
		}
		else {
			var callee = _module.Functions.FirstOrDefault(f => f.MangledName == c.MangledName);
			argTypes = callee != null ? callee.Parameters.Select(p => LlvmType(p.Type)).ToList() : Enumerable.Repeat("ptr", c.Args.Count).ToList();
			while (argTypes.Count < c.Args.Count) argTypes.Add("ptr");
		}

		var argVals = c.Args.Select(EmitExpr).ToList();
		var argList = string.Join(", ", argVals.Select((v, i) => $"{argTypes[i]} {v}"));

		string retTy;
		var registered = _module.Functions.FirstOrDefault(f => f.MangledName == c.MangledName);
		retTy = registered != null ? LlvmType(registered.ReturnType) : "void";

		string fnTypePrefix = "";
		if (isVariadic) {
			var leadCount = _variadicLeading[c.MangledName];
			var leadingTypes = string.Join(", ", argTypes.Take(leadCount));
			fnTypePrefix = leadCount == 0 ? " (...)" : $" ({leadingTypes}, ...)";
		}

		if (retTy == "void") {
			_bodyLines.Add($"  call void{fnTypePrefix} @{llvmName}({argList})");
			return "void";
		}

		var t = FreshTemp();
		_bodyLines.Add($"  {t} = call {retTy}{fnTypePrefix} @{llvmName}({argList})");
		return t;
	}

	// Virtual dispatch through the receiver's `__vtable__` header. Loads the vtable pointer
	// from offset 0 of the receiver, GEPs to the global slot, loads the function pointer,
	// and calls it with the receiver passed as the implicit `this` argument.
	private string EmitVirtualCall(CirExpr.VirtualCall vc) {
		var receiver = EmitExpr(vc.Receiver);
		// Load the vtable pointer from the receiver's header (offset 0).
		var vtablePtr = FreshTemp();
		_bodyLines.Add($"  {vtablePtr} = load ptr, ptr {receiver}, align 8");
		// GEP into the vtable's methods array. The vtable struct shape is `{ ptr, [N x ptr] }`
		// — the leading `ptr` is the parent-class vtable used for inheritance walks; field 1
		// is the interface-method array. Use any size >= SlotId+1 so the GEP is well-typed.
		var slotAddr = FreshTemp();
		var vsize = vc.SlotId + 1;
		_bodyLines.Add($"  {slotAddr} = getelementptr {{ ptr, [{vsize} x ptr] }}, ptr {vtablePtr}, i32 0, i32 1, i32 {vc.SlotId}");
		// Load the function pointer from the slot.
		var fnPtr = FreshTemp();
		_bodyLines.Add($"  {fnPtr} = load ptr, ptr {slotAddr}, align 8");

		// Indirect call. Receiver is the first arg (`this`); user args follow. The function
		// type signature is derived from the VirtualCall's recorded CIR return + param types.
		var argVals = vc.Args.Select(EmitExpr).ToList();
		var paramSigParts = new List<string> { "ptr" };
		paramSigParts.AddRange(vc.ParamTypes.Select(LlvmType));
		var fnType = $"{LlvmType(vc.ReturnType)} ({string.Join(", ", paramSigParts)})";
		var argList = string.Join(", ", new[] { $"ptr {receiver}" }.Concat(argVals.Select((v, i) => $"{LlvmType(vc.ParamTypes[i])} {v}")));
		var retTy = LlvmType(vc.ReturnType);
		if (retTy == "void") {
			_bodyLines.Add($"  call {fnType} {fnPtr}({argList})");
			return "void";
		}

		var t = FreshTemp();
		_bodyLines.Add($"  {t} = call {fnType} {fnPtr}({argList})");
		return t;
	}

	// Emit the runtime parent-chain walk for class identity checks. Loads the receiver's
	// vtable, compares against the target's vtable global, and on mismatch loads the
	// parent slot and loops. Returns `(hitLabel, missLabel)` — labels at which the caller
	// must terminate each branch with the appropriate result handling.
	//
	// Loop shape:
	//   entry:    vt0 = load receiver; br loop
	//   loop:     cur = phi [vt0, entry], [parent, iter]
	//             match = icmp eq cur, target
	//             br match → hit | check_null
	//   check_null: isnull = icmp eq cur, null
	//             br isnull → miss | iter
	//   iter:     parent_addr = gep cur, field 0
	//             parent = load
	//             br loop
	//   hit:      <caller's success branch>
	//   miss:     <caller's failure branch>
	private (string hitLabel, string missLabel) EmitVtableChainSearch(string receiver, string targetVtableSym) {
		var entryLabel = FreshLabel("cast_entry");
		var loopLabel = FreshLabel("cast_loop");
		var iterLabel = FreshLabel("cast_iter");
		var checkNullLabel = FreshLabel("cast_chknull");
		var hitLabel = FreshLabel("cast_hit");
		var missLabel = FreshLabel("cast_miss");

		var initVt = FreshTemp();
		var cur = FreshTemp();
		var match = FreshTemp();
		var isNull = FreshTemp();
		var parentAddr = FreshTemp();
		var parent = FreshTemp();
		var vsize = VtableSlotCount();

		_bodyLines.Add($"  br label %{entryLabel}");
		_bodyLines.Add($"{entryLabel}:");
		_bodyLines.Add($"  {initVt} = load ptr, ptr {receiver}, align 8");
		_bodyLines.Add($"  br label %{loopLabel}");

		_bodyLines.Add($"{loopLabel}:");
		_bodyLines.Add($"  {cur} = phi ptr [{initVt}, %{entryLabel}], [{parent}, %{iterLabel}]");
		_bodyLines.Add($"  {match} = icmp eq ptr {cur}, {targetVtableSym}");
		_bodyLines.Add($"  br i1 {match}, label %{hitLabel}, label %{checkNullLabel}");

		_bodyLines.Add($"{checkNullLabel}:");
		_bodyLines.Add($"  {isNull} = icmp eq ptr {cur}, null");
		_bodyLines.Add($"  br i1 {isNull}, label %{missLabel}, label %{iterLabel}");

		_bodyLines.Add($"{iterLabel}:");
		_bodyLines.Add($"  {parentAddr} = getelementptr {{ ptr, [{vsize} x ptr] }}, ptr {cur}, i32 0, i32 0");
		_bodyLines.Add($"  {parent} = load ptr, ptr {parentAddr}, align 8");
		_bodyLines.Add($"  br label %{loopLabel}");

		return (hitLabel, missLabel);
	}

	// `x as T` / `x as? T` for reference downcasts. The chain-walk loop searches the
	// receiver's class and every ancestor for a vtable matching the target. On match the
	// receiver is the answer; on mismatch `as` aborts and `as?` yields null.
	private string EmitDowncast(CirExpr.Downcast dc) {
		var receiver = EmitExpr(dc.Receiver);
		var (hitLabel, missLabel) = EmitVtableChainSearch(receiver, $"@{MangleVtableGlobal(dc.TargetClassFqn)}");

		if (dc.IsSafe) {
			var doneLabel = FreshLabel("cast_done");
			_bodyLines.Add($"{hitLabel}:");
			_bodyLines.Add($"  br label %{doneLabel}");
			_bodyLines.Add($"{missLabel}:");
			_bodyLines.Add($"  br label %{doneLabel}");
			_bodyLines.Add($"{doneLabel}:");
			_blockTerminated = false;
			var result = FreshTemp();
			_bodyLines.Add($"  {result} = phi ptr [{receiver}, %{hitLabel}], [null, %{missLabel}]");
			return result;
		}

		// Unsafe `as` — abort on miss. The miss block is unreachable after `abort()`, so
		// control only continues from the hit block.
		_bodyLines.Add($"{missLabel}:");
		_bodyLines.Add("  call void @abort()");
		_bodyLines.Add("  unreachable");
		_bodyLines.Add($"{hitLabel}:");
		_blockTerminated = false;
		return receiver;
	}

	// `x is T` — runtime kind check. Walks the same chain as the downcast and returns `i1`
	// (true on match, false on miss). Restricted to class targets; the analyzer rejects
	// other combinations with S01F before reaching here.
	private string EmitTypeCheck(CirExpr.TypeCheck tc) {
		if (tc.TargetType is not CirType.Named { FullyQualifiedName: var targetFqn } || !_classByFqn.ContainsKey(targetFqn)) {
			LlvmError.UnsupportedExpression.WithMessage("`is` target must be a known class").Render();
			return "0";
		}
		var receiver = EmitExpr(tc.Value);
		var (hitLabel, missLabel) = EmitVtableChainSearch(receiver, $"@{MangleVtableGlobal(targetFqn)}");
		var doneLabel = FreshLabel("is_done");
		_bodyLines.Add($"{hitLabel}:");
		_bodyLines.Add($"  br label %{doneLabel}");
		_bodyLines.Add($"{missLabel}:");
		_bodyLines.Add($"  br label %{doneLabel}");
		_bodyLines.Add($"{doneLabel}:");
		_blockTerminated = false;
		var result = FreshTemp();
		_bodyLines.Add($"  {result} = phi i1 [1, %{hitLabel}], [0, %{missLabel}]");
		return result;
	}

	// `x ?? y` — null-coalesce. Yields `x` when non-null, otherwise the value of `y`. Both
	// branches store into a stack slot; mem2reg promotes the alloca/store/load pattern back
	// to a phi during clang's optimization passes. The slot lets us handle right-hand sides
	// that branch internally (nested `??`, ternary, etc.) without tracking the current
	// basic block label by hand. Restricted to pointer-typed nullables for now.
	private string EmitNullCoalesce(CirExpr.NullCoalesce nc) {
		var leftTy = LlvmTypeOf(nc.Left);
		if (leftTy != "ptr") {
			LlvmError.UnsupportedExpression.WithMessage($"`??` on non-pointer nullable type '{leftTy}' is not yet supported").Render();
			return "undef";
		}

		// Stack slot for the coalesced result. Allocated up front so both branches share it.
		var resultAddr = $"%coalesce_result.{_tempCounter++}";
		_allocaLines.Add($"  {resultAddr} = alloca {leftTy}, align 8");

		var leftVal = EmitExpr(nc.Left);
		var rightLabel = FreshLabel("coalesce_right");
		var leftLabel = FreshLabel("coalesce_left");
		var doneLabel = FreshLabel("coalesce_done");

		var isNull = FreshTemp();
		_bodyLines.Add($"  {isNull} = icmp eq {leftTy} {leftVal}, null");
		_bodyLines.Add($"  br i1 {isNull}, label %{rightLabel}, label %{leftLabel}");

		// Right branch: evaluate the fallback and store it into the slot.
		_bodyLines.Add($"{rightLabel}:");
		_blockTerminated = false;
		var rightVal = EmitExpr(nc.Right);
		_bodyLines.Add($"  store {leftTy} {rightVal}, ptr {resultAddr}");
		_bodyLines.Add($"  br label %{doneLabel}");

		// Left branch: store the original (non-null) left value.
		_bodyLines.Add($"{leftLabel}:");
		_blockTerminated = false;
		_bodyLines.Add($"  store {leftTy} {leftVal}, ptr {resultAddr}");
		_bodyLines.Add($"  br label %{doneLabel}");

		// Merge: load whichever was stored.
		_bodyLines.Add($"{doneLabel}:");
		_blockTerminated = false;
		var result = FreshTemp();
		_bodyLines.Add($"  {result} = load {leftTy}, ptr {resultAddr}");
		return result;
	}

	// `new ClassName(args)` — heap-allocate a zero-initialized instance, run its constructor,
	// return the pointer. Memory model: `calloc(1, sizeof(struct))` guarantees zero bits, so
	// fields without explicit initializers come up as 0/null/false. Lifetime is unmanaged
	// (leaks until explicit `delete`).
	private string EmitAlloc(CirExpr.Alloc a) {
		if (a.Type is not CirType.Named named) {
			LlvmError.UnsupportedExpression.WithMessage($"alloc target must be a named class type, got {a.Type.GetType().Name}").Render();
			return "undef";
		}

		var fqn = named.FullyQualifiedName;
		var structName = StructName(fqn);

		// Compute sizeof(struct) via the GEP-null trick: pointer to element index 1 of a null
		// pointer is the byte offset of one struct, i.e. its size. ptrtoint converts to i64.
		var sizePtr = FreshTemp();
		_bodyLines.Add($"  {sizePtr} = getelementptr {structName}, ptr null, i32 1");
		var sizeI64 = FreshTemp();
		_bodyLines.Add($"  {sizeI64} = ptrtoint ptr {sizePtr} to i64");

		// Heap allocation. calloc zeroes the memory, satisfying the "fields default to zero" rule
		// without an additional memset.
		var obj = FreshTemp();
		_bodyLines.Add($"  {obj} = call ptr @calloc(i64 1, i64 {sizeI64})");

		// Constructor invocation. Receiver (`this`) is the first arg; user-supplied args follow.
		// Argument LLVM types come from the constructor's registered signature when available.
		var ctorLlvm = MangleToLlvm(a.CtorMangledName);
		var argVals = a.Args.Select(EmitExpr).ToList();
		var argTypes = ResolveCallArgTypes(a.CtorMangledName, argVals.Count, skipReceiver: true);
		var argList = string.Join(", ", new[] { $"ptr {obj}" }.Concat(argVals.Select((v, i) => $"{argTypes[i]} {v}")));
		_bodyLines.Add($"  call void @{ctorLlvm}({argList})");

		return obj;
	}

	// Look up an LLVM-typed argument list for a callee, optionally skipping the leading `this`.
	// Falls back to opaque `ptr` when the callee isn't in the module table.
	private List<string> ResolveCallArgTypes(string mangledName, int count, bool skipReceiver) {
		var fn = _module.Functions.FirstOrDefault(f => f.MangledName == mangledName);
		if (fn == null) return Enumerable.Repeat("ptr", count).ToList();
		var src = skipReceiver ? fn.Parameters.Skip(1) : fn.Parameters;
		var types = src.Select(p => LlvmType(p.Type)).ToList();
		while (types.Count < count) types.Add("ptr");
		return types.Take(count).ToList();
	}

	// LLVM type of an expression's runtime value, used when typing variadic arguments
	// and call-site argument lists. Locals/this are looked up in _localTypeMap; literals
	// are typed by their CIR variant; Cast carries an explicit target type.
	private string LlvmTypeOf(CirExpr expr) => expr switch {
		// Integer literals follow the smallest-signed-fit rule used by CIR's TypeInference,
		// keeping LLVM and CIR's type views consistent (e.g. `let x = 5 + 5` is i8 in both layers).
		CirExpr.IntLit i => LlvmType(new CirType.Named(TypeInference.SmallestSignedFit(i.Value))),
		CirExpr.FloatLit => "double",
		CirExpr.BoolLit => "i1",
		CirExpr.CharLit => "i8",
		CirExpr.StrLit => "ptr",
		CirExpr.NullLit => "ptr",
		CirExpr.Local l when _localTypeMap.TryGetValue(l.Name, out var ty) => LlvmType(ty),
		CirExpr.ThisPtr => "ptr",
		CirExpr.Cast cast => LlvmType(cast.TargetType),
		// Field access: walk the chain, look up the named field's type in the parent class's
		// declared field list. Falls back to ptr if any link in the chain can't be resolved.
		CirExpr.FieldAccess fa => ResolveTargetFqn(fa.Target) is { } parentFqn && _classByFqn.TryGetValue(parentFqn, out var parentCls) && parentCls.Fields.FirstOrDefault(f => f.Name == fa.FieldName) is { } fld ? LlvmType(fld.Type) : "ptr",
		// Comparisons produce i1; Pow always widens to i64 (integer ops) or double (any
		// float op) so the helper / libm result isn't truncated. Other arithmetic
		// produces the wider operand's LLVM type.
		CirExpr.Binary b => IsComparisonBinOp(b.Op) ? "i1"
			: b.Op == CirBinOp.Pow
				? (IsIntegerLlvmType(LlvmTypeOf(b.Left)) && IsIntegerLlvmType(LlvmTypeOf(b.Right)) ? "i64" : "double")
				: WiderLlvmType(LlvmTypeOf(b.Left), LlvmTypeOf(b.Right)),
		// Unary Neg/BitNot keep the operand's type; logical Not is always i1.
		CirExpr.Unary u => u.Op == CirUnOp.Not ? "i1" : LlvmTypeOf(u.Operand),
		// Static-field loads carry their declared type on the CIR node.
		CirExpr.StaticFieldRef sr => LlvmType(sr.Type),
		// Enum case references are pointers to the per-case constant global.
		CirExpr.EnumCaseRef => "ptr",
		// Look up the callee's return type from the module's function table; fall back to ptr
		// for unresolved/unknown calls.
		CirExpr.Call call => _module.Functions.FirstOrDefault(f => f.MangledName == call.MangledName) is { } fn ? LlvmType(fn.ReturnType) : "ptr",
		// Vtable references are opaque pointers at runtime; virtual call type is recorded.
		CirExpr.VtableRef => "ptr",
		CirExpr.VirtualCall vc => LlvmType(vc.ReturnType),
		// Downcast yields a pointer (or null for `as?`); TypeCheck is i1.
		CirExpr.Downcast => "ptr",
		CirExpr.TypeCheck => "i1",
		_ => "ptr"
	};

	private static string WiderLlvmType(string a, string b) =>
		a == b ? a : (BitWidth(a) >= BitWidth(b) ? a : b);

	private static bool IsComparisonBinOp(CirBinOp op) =>
		op is CirBinOp.Eq or CirBinOp.NotEq or CirBinOp.Lt or CirBinOp.LtEq or CirBinOp.Gt or CirBinOp.GtEq or CirBinOp.In;

	// Emit a CIR cast to LLVM IR. Supports lossless integer widening (sext for signed,
	// zext for unsigned), float widening (fpext), and integer↔float conversions (sitofp/fptosi).
	private string EmitCast(CirExpr.Cast cast) {
		var dstTy = LlvmType(cast.TargetType);

		// Integer-typed literals are width-agnostic in LLVM IR. When widening such a literal
		// to any integer type, return the literal value directly — avoids `sext i8 5 to i32`
		// boilerplate that would otherwise pepper the output.
		if (dstTy is "i1" or "i8" or "i16" or "i32" or "i64") {
			if (cast.Value is CirExpr.IntLit i) return i.Value;
			if (cast.Value is CirExpr.BoolLit b) return b.Value ? "1" : "0";
			if (cast.Value is CirExpr.CharLit c) return ((int)c.Value).ToString(CultureInfo.InvariantCulture);
		}

		var srcVal = EmitExpr(cast.Value);
		var srcTy = LlvmTypeOf(cast.Value);

		if (srcTy == dstTy) return srcVal;

		var dstName = (cast.TargetType as CirType.Named)?.FullyQualifiedName ?? "";
		var dstSigned = dstName is "i8" or "i16" or "i32" or "i64" or "int" or "long" or "short";
		var t = FreshTemp();

		if (srcTy is "i1" or "i8" or "i16" or "i32" or "i64" && dstTy is "i8" or "i16" or "i32" or "i64") {
			var op = dstSigned ? "sext" : "zext";
			// Same-width src/dst already short-circuited above. Narrowing is not lossless and
			// shouldn't be reachable from the dispatch path; emit truncate as a fallback.
			if (BitWidth(srcTy) > BitWidth(dstTy))
				_bodyLines.Add($"  {t} = trunc {srcTy} {srcVal} to {dstTy}");
			else
				_bodyLines.Add($"  {t} = {op} {srcTy} {srcVal} to {dstTy}");
			return t;
		}

		if (srcTy == "float" && dstTy == "double") {
			_bodyLines.Add($"  {t} = fpext float {srcVal} to double");
			return t;
		}

		if (srcTy == "double" && dstTy == "float") {
			_bodyLines.Add($"  {t} = fptrunc double {srcVal} to float");
			return t;
		}

		// Integer → float. Default to `sitofp` (signed) since unsigned source tracking isn't
		// fully wired through; revisit when u32/u64 → float casts need unsigned semantics.
		if (srcTy is "i1" or "i8" or "i16" or "i32" or "i64" && dstTy is "float" or "double") {
			_bodyLines.Add($"  {t} = sitofp {srcTy} {srcVal} to {dstTy}");
			return t;
		}

		if (srcTy is "float" or "double" && dstTy is "i8" or "i16" or "i32" or "i64") {
			_bodyLines.Add($"  {t} = fptosi {srcTy} {srcVal} to {dstTy}");
			return t;
		}

		// Catch-all bitcast for unhandled cases — keeps compilation moving and surfaces
		// any miscoercions as obvious LLVM errors rather than mysterious crashes.
		_bodyLines.Add($"  {t} = bitcast {srcTy} {srcVal} to {dstTy}");
		return t;
	}

	private static int BitWidth(string llvmType) => llvmType switch {
		"i1" => 1, "i8" => 8, "i16" => 16, "i32" => 32, "i64" => 64,
		"float" => 32, "double" => 64,
		_ => 0
	};

	private string EmitBinary(CirExpr.Binary b) {
		// Power doesn't fit the simple binop shape — route to a helper or libm.
		if (b.Op == CirBinOp.Pow) return EmitPow(b);
		// Pick the wider operand type for arithmetic so i64/f64 expressions emit the right binop.
		var leftTy = LlvmTypeOf(b.Left);
		var rightTy = LlvmTypeOf(b.Right);
		var opTy = WiderLlvmType(leftTy, rightTy);
		var lhs = EmitExpr(b.Left);
		var rhs = EmitExpr(b.Right);
		// LLVM requires matching types on both sides of a binop. Widen any narrower
		// operand to `opTy` so a mix like `i8 + i64` (e.g. after a Pow widens one side)
		// emits as `i64 + i64`.
		lhs = CoerceTo(lhs, leftTy, opTy);
		rhs = CoerceTo(rhs, rightTy, opTy);
		var t = FreshTemp();
		_bodyLines.Add($"  {t} = {LlvmBinOp(b.Op, opTy)} {opTy} {lhs}, {rhs}");
		return t;
	}

	// True when an LLVM scalar type is integer (i1/i8/i16/i32/i64). False for floats and ptr.
	private static bool IsIntegerLlvmType(string ty) =>
		ty is "i1" or "i8" or "i16" or "i32" or "i64";

	// Lower `base ^ exp` (power). Integer-integer routes through the module helper
	// `@cloth_pow_i64` (exponentiation by squaring) and stays i64. Anything involving
	// a float coerces both sides to double and calls libm `pow`, returning double.
	// The typer matches this rule (Pow result is i64 or f64), so the surrounding store
	// or binop sees the right width and the result isn't truncated.
	private string EmitPow(CirExpr.Binary b) {
		var leftTy = LlvmTypeOf(b.Left);
		var rightTy = LlvmTypeOf(b.Right);
		var lhs = EmitExpr(b.Left);
		var rhs = EmitExpr(b.Right);

		if (IsIntegerLlvmType(leftTy) && IsIntegerLlvmType(rightTy)) {
			_needsIntPowHelper = true;
			var lhs64 = WidenIntTo(lhs, leftTy, "i64");
			var rhs64 = WidenIntTo(rhs, rightTy, "i64");
			var call = FreshTemp();
			_bodyLines.Add($"  {call} = call i64 @cloth_pow_i64(i64 {lhs64}, i64 {rhs64})");
			return call;
		}

		// Float path: lift any integer operand to double, call libm `pow`, return double.
		_needsLibmPow = true;
		var lhsD = ToDouble(lhs, leftTy);
		var rhsD = ToDouble(rhs, rightTy);
		var resD = FreshTemp();
		_bodyLines.Add($"  {resD} = call double @pow(double {lhsD}, double {rhsD})");
		return resD;
	}

	// Coerce an emitted value `val` (currently of `fromTy`) to `toTy`. Used by
	// `EmitBinary` so binops see operands of matching widths, which LLVM requires.
	// Handles integer width changes (sext/trunc), float width changes (fpext/fptrunc),
	// and int↔float crossings (sitofp/fptosi). Same-type pass-through returns the
	// original SSA name.
	private string CoerceTo(string val, string fromTy, string toTy) {
		if (fromTy == toTy) return val;
		if (IsIntegerLlvmType(fromTy) && IsIntegerLlvmType(toTy))
			return BitWidth(toTy) > BitWidth(fromTy) ? WidenIntTo(val, fromTy, toTy) : NarrowIntTo(val, fromTy, toTy);
		if (toTy == "double") return ToDouble(val, fromTy);
		if (toTy == "float") {
			var asD = ToDouble(val, fromTy);
			return CoerceTo(asD, "double", "float");
		}
		if (fromTy is "double" or "float" && IsIntegerLlvmType(toTy)) return FromDouble(val, toTy);
		return val;
	}

	private string WidenIntTo(string val, string fromTy, string toTy) {
		if (fromTy == toTy) return val;
		var t = FreshTemp();
		_bodyLines.Add($"  {t} = sext {fromTy} {val} to {toTy}");
		return t;
	}

	private string NarrowIntTo(string val, string fromTy, string toTy) {
		if (fromTy == toTy) return val;
		var t = FreshTemp();
		_bodyLines.Add($"  {t} = trunc {fromTy} {val} to {toTy}");
		return t;
	}

	private string ToDouble(string val, string fromTy) {
		if (fromTy == "double") return val;
		var t = FreshTemp();
		if (fromTy == "float") _bodyLines.Add($"  {t} = fpext float {val} to double");
		else if (IsIntegerLlvmType(fromTy)) _bodyLines.Add($"  {t} = sitofp {fromTy} {val} to double");
		else _bodyLines.Add($"  {t} = bitcast {fromTy} {val} to double"); // fallback; shouldn't hit
		return t;
	}

	private string FromDouble(string val, string toTy) {
		if (toTy == "double") return val;
		var t = FreshTemp();
		if (toTy == "float") _bodyLines.Add($"  {t} = fptrunc double {val} to float");
		else if (IsIntegerLlvmType(toTy)) _bodyLines.Add($"  {t} = fptosi double {val} to {toTy}");
		else _bodyLines.Add($"  {t} = bitcast double {val} to {toTy}");
		return t;
	}

	private string EmitUnary(CirExpr.Unary u) {
		// Pre/post increment/decrement run on an lvalue: load, compute, store, return the
		// value matching the operator's semantics (post returns the old value, pre returns
		// the new). Operates on integer types only — float `++` is not supported in CIR yet.
		if (u.Op is CirUnOp.PostInc or CirUnOp.PostDec or CirUnOp.PreInc or CirUnOp.PreDec) {
			var addr = EmitAddrOf(u.Operand);
			var (lvalueTy, _) = TypeOfLvalue(u.Operand);
			var llvmTy = LlvmType(lvalueTy);
			var oldVal = FreshTemp();
			_bodyLines.Add($"  {oldVal} = load {llvmTy}, ptr {addr}");
			var newVal = FreshTemp();
			var op = u.Op is CirUnOp.PostInc or CirUnOp.PreInc ? "add" : "sub";
			_bodyLines.Add($"  {newVal} = {op} {llvmTy} {oldVal}, 1");
			_bodyLines.Add($"  store {llvmTy} {newVal}, ptr {addr}");
			return u.Op is CirUnOp.PostInc or CirUnOp.PostDec ? oldVal : newVal;
		}

		// Use the operand's actual LLVM type for Neg / BitNot so the result matches the
		// surrounding arithmetic width — `let x = a + -10;` infers the literal `10` as
		// i8 (smallest fit), and `-10` must come back as i8 too, not a hardcoded i32.
		// Logical Not always produces i1 regardless of operand width.
		var operandTy = LlvmTypeOf(u.Operand);
		var operand = EmitExpr(u.Operand);
		var t = FreshTemp();
		switch (u.Op) {
			case CirUnOp.Neg:
				_bodyLines.Add($"  {t} = sub {operandTy} 0, {operand}");
				return t;
			case CirUnOp.Not:
				_bodyLines.Add($"  {t} = xor i1 {operand}, true");
				return t;
			case CirUnOp.BitNot:
				_bodyLines.Add($"  {t} = xor {operandTy} {operand}, -1");
				return t;
		}

		LlvmError.UnsupportedExpression.WithMessage($"unary operator {u.Op} not yet lowered").Render();
		return "undef";
	}

	// Address-of for an lvalue expression (assignment target).
	private string EmitAddrOf(CirExpr expr) {
		switch (expr) {
			case CirExpr.Local l:
				if (_localAddrMap.TryGetValue(l.Name, out var addr)) return addr;
				LlvmError.UnsupportedExpression.WithMessage($"address-of unknown local '{l.Name}'").Render();
				return "undef";
			case CirExpr.FieldAccess fa: return EmitFieldGep(fa).gep;
		}

		LlvmError.UnsupportedExpression.WithMessage($"cannot take address of {expr.GetType().Name}").Render();
		return "undef";
	}

	private (CirType type, bool found) TypeOfLvalue(CirExpr expr) {
		switch (expr) {
			case CirExpr.Local l:
				return _localTypeMap.TryGetValue(l.Name, out var ty) ? (ty, true) : (new CirType.Any(), false);
			case CirExpr.FieldAccess fa:
				var fqn = ResolveTargetFqn(fa.Target);
				if (fqn != null && _classByFqn.ContainsKey(fqn)) {
					var f = GetFlattenedFields(fqn).FirstOrDefault(x => x.Name == fa.FieldName);
					if (f != null) return (f.Type, true);
				}
				if (fqn != null && _enumByFqn.TryGetValue(fqn, out var enumDecl)) {
					var (idx, fieldTy) = ResolveEnumFieldIndex(enumDecl, fa.FieldName);
					if (idx >= 0) return (fieldTy, true);
				}

				return (new CirType.Any(), false);
		}

		return (new CirType.Any(), false);
	}

	private string? ResolveTargetFqn(CirExpr target) => target switch {
		CirExpr.ThisPtr => _currentThisFqn,
		CirExpr.Local l when _localTypeMap.TryGetValue(l.Name, out var ty) => ty is CirType.Ptr p && p.Inner is CirType.Named np ? np.FullyQualifiedName : ty is CirType.Named n ? n.FullyQualifiedName : null,
		// Enum case singletons: the FQN of the value is the enum's FQN. Used by method
		// calls on `EnumName.CASE.someGetter()`.
		CirExpr.EnumCaseRef ec => ec.EnumFqn,
		// Nested field-access chains (e.g. `this.__outer__.outerField`): resolve the inner
		// FieldAccess to its containing class, then look up the named field via the
		// flattened layout (so an ancestor-declared field still resolves).
		CirExpr.FieldAccess fa when ResolveTargetFqn(fa.Target) is { } parentFqn && _classByFqn.ContainsKey(parentFqn) => GetFlattenedFields(parentFqn).FirstOrDefault(f => f.Name == fa.FieldName)?.Type is CirType.Named fn ? fn.FullyQualifiedName : null,
		_ => null
	};

	// -------------------------------------------------------------------------
	// String pool
	// -------------------------------------------------------------------------

	private string InternString(string value) {
		// Already collected during pre-scan.
		var idx = _stringIndex[value];
		var (_, byteCount) = EncodeStringConstant(value);
		var t = FreshTemp();
		_bodyLines.Add($"  {t} = getelementptr inbounds [{byteCount} x i8], ptr @.str.{idx}, i32 0, i32 0");
		return t;
	}

	private static (string encoded, int byteCount) EncodeStringConstant(string value) {
		var bytes = Encoding.UTF8.GetBytes(value);
		var sb = new StringBuilder(bytes.Length + 1);
		foreach (var b in bytes) {
			if (b == '\\' || b == '"' || b < 0x20 || b > 0x7e)
				sb.Append('\\').Append(b.ToString("X2"));
			else
				sb.Append((char)b);
		}

		sb.Append("\\00");
		return (sb.ToString(), bytes.Length + 1);
	}

	// -------------------------------------------------------------------------
	// Type / op mapping
	// -------------------------------------------------------------------------

	private static string LlvmType(CirType t) => t switch {
		CirType.Void => "void",
		CirType.Any => "ptr",
		CirType.Ptr => "ptr",
		CirType.Nullable n => LlvmType(n.Inner),
		CirType.Array => "ptr",
		CirType.Tuple => "ptr",
		CirType.Generic => "ptr",
		CirType.Named n => n.FullyQualifiedName switch {
			// Canonical primitive types (also produced by SemanticAnalyzer aliasing).
			"i8" or "u8" => "i8",
			"i16" or "u16" => "i16",
			"i32" or "u32" => "i32",
			"i64" or "u64" => "i64",
			"f32" => "float",
			"f64" => "double",
			// Aliases — kept for back-compat with code that hasn't been canonicalized.
			"int" => "i32",
			"uint" => "i32",
			"unsigned" => "i32",
			"long" => "i64",
			"short" => "i16",
			"float" => "float",
			"double" => "double",
			"real" => "double",
			// Other primitives.
			"string" => "ptr",
			"byte" => "i8",
			"sbyte" => "i8",
			"char" => "i8",
			"bool" => "i1",
			"bit" => "i1",
			"void" => "void",
			"any" => "ptr",
			_ => "ptr"
		},
		_ => "ptr"
	};

	private static string DefaultValue(CirType t) => t switch {
		CirType.Named n when n.FullyQualifiedName is "i8" or "i16" or "i32" or "i64" or "u8" or "u16" or "u32" or "u64" or "int" or "uint" or "unsigned" or "long" or "short" or "byte" or "sbyte" or "char" or "bit" => "0",
		CirType.Named n when n.FullyQualifiedName is "bool" => "0",
		CirType.Named n when n.FullyQualifiedName is "f32" or "f64" or "float" or "double" or "real" => "0.0",
		_ => "null"
	};

	private static string LlvmBinOp(CirBinOp op, string ty) {
		var isFloat = ty is "float" or "double";
		return op switch {
			CirBinOp.Add => isFloat ? "fadd" : "add",
			CirBinOp.Sub => isFloat ? "fsub" : "sub",
			CirBinOp.Mul => isFloat ? "fmul" : "mul",
			CirBinOp.Div => isFloat ? "fdiv" : "sdiv",
			CirBinOp.Rem => isFloat ? "frem" : "srem",
			CirBinOp.BitAnd or CirBinOp.And => "and",
			CirBinOp.BitOr or CirBinOp.Or => "or",
			CirBinOp.Shl => "shl",
			CirBinOp.Shr => "ashr",
			CirBinOp.Eq => isFloat ? "fcmp oeq" : "icmp eq",
			CirBinOp.NotEq => isFloat ? "fcmp one" : "icmp ne",
			CirBinOp.Lt => isFloat ? "fcmp olt" : "icmp slt",
			CirBinOp.LtEq => isFloat ? "fcmp ole" : "icmp sle",
			CirBinOp.Gt => isFloat ? "fcmp ogt" : "icmp sgt",
			CirBinOp.GtEq => isFloat ? "fcmp oge" : "icmp sge",
			_ => "add"
		};
	}

	private static CirBinOp AssignToBinOp(CirAssignOp op) => op switch {
		CirAssignOp.AddAssign => CirBinOp.Add,
		CirAssignOp.SubAssign => CirBinOp.Sub,
		CirAssignOp.MulAssign => CirBinOp.Mul,
		CirAssignOp.DivAssign => CirBinOp.Div,
		CirAssignOp.RemAssign => CirBinOp.Rem,
		CirAssignOp.AndAssign => CirBinOp.BitAnd,
		CirAssignOp.OrAssign => CirBinOp.BitOr,
		CirAssignOp.PowAssign => CirBinOp.Pow,
		_ => CirBinOp.Add
	};

	// -------------------------------------------------------------------------
	// Name mangling helpers
	// -------------------------------------------------------------------------

	private static string MangleToLlvm(string cirName) {
		var parts = cirName.Split('.');
		for (var i = 0; i < parts.Length; i++)
			if (parts[i].StartsWith('~'))
				parts[i] = "dtor_" + parts[i][1..];
		// LLVM symbol names accept letters, digits, `_`, `.`, `$`, `-`. Array brackets in
		// canonical type names (e.g. `string[]` from a primary param) need encoding.
		return string.Join('_', parts).Replace("[]", "_arr").Replace('[', '_').Replace(']', '_');
	}

	private static string StructName(string fqn) => "%struct." + MangleToLlvm(fqn);

	private string FreshTemp() => $"%_t{_tempCounter++}";
}