// Copyright (c) 2026.The Cloth contributors.
// 
// Operators.cs is part of the Cloth Frontend.
// 
// Use, modification, and distribution of this file are governed by the
// license terms provided with the Cloth Compiler source distribution.

namespace FrontEnd.Token;

public enum Operator {
	DotDotDot,
	DotDot,
	ColonColon,
	ReturnArrow,
	Arrow,
	Fallback,
	PlusPlus,
	MinusMinus,
	PlusEqual,
	MinusEqual,
	StarEqual,
	SlashEqual,
	PercentEqual,
	AndEqual,
	OrEqual,
	CaretEqual,
	EqualEqual,
	NotEqual,
	LessEqual,
	GreaterEqual,
	Equal,
	Less,
	Greater,
	Plus,
	Minus,
	Star,
	Slash,
	Percent,
	And,
	Or,
	Caret,
	Tilde,
	Not,
	Dot,
	Comma,
	Semicolon,
	Colon,
	LParen,
	RParen,
	LBrace,
	RBrace,
	LBracket,
	RBracket,
	At,
	Hash,
	Dollar,
	Question,
	Backtick
}

public static class Operators {
	public static readonly string[] MultiCharOperators = new[] {
		"...", "..", "::", ":>", "->", "=>", "??",
		"++", "--", "+=", "-=", "*=", "/=", "%=",
		"&=", "|=", "^=", "==", "!=", "<=", ">="
	};

	public static readonly char[] SingleCharOperators = new[] {
		'=', '<', '>', '+', '-', '*', '/', '%',
		'&', '|', '^', '~', '!', '.', ',', ';',
		':', '(', ')', '{', '}', '[', ']', '@',
		'#', '$', '?', '`'
	};

	public static Operator GetOperatorFromLexeme(string lexeme) {
		return lexeme switch {
			"..." => Operator.DotDotDot,
			".." => Operator.DotDot,
			"::" => Operator.ColonColon,
			":>" => Operator.ReturnArrow,
			"->" => Operator.Arrow,
			"??" => Operator.Fallback,
			"++" => Operator.PlusPlus,
			"--" => Operator.MinusMinus,
			"+=" => Operator.PlusEqual,
			"-=" => Operator.MinusEqual,
			"*=" => Operator.StarEqual,
			"/=" => Operator.SlashEqual,
			"%=" => Operator.PercentEqual,
			"&=" => Operator.AndEqual,
			"|=" => Operator.OrEqual,
			"^=" => Operator.CaretEqual,
			"==" => Operator.EqualEqual,
			"!=" => Operator.NotEqual,
			"<=" => Operator.LessEqual,
			">=" => Operator.GreaterEqual,
			"=" => Operator.Equal,
			"<" => Operator.Less,
			">" => Operator.Greater,
			"+" => Operator.Plus,
			"-" => Operator.Minus,
			"*" => Operator.Star,
			"/" => Operator.Slash,
			"%" => Operator.Percent,
			"&" => Operator.And,
			"|" => Operator.Or,
			"^" => Operator.Caret,
			"~" => Operator.Tilde,
			"!" => Operator.Not,
			"." => Operator.Dot,
			"," => Operator.Comma,
			";" => Operator.Semicolon,
			":" => Operator.Colon,
			"(" => Operator.LParen,
			")" => Operator.RParen,
			"{" => Operator.LBrace,
			"}" => Operator.RBrace,
			"[" => Operator.LBracket,
			"]" => Operator.RBracket,
			"@" => Operator.At,
			"#" => Operator.Hash,
			"$" => Operator.Dollar,
			"?" => Operator.Question,
			"`" => Operator.Backtick,
			_ => throw new NotImplementedException()
		};
	}

	public static string GetLexemeFromOperator(Operator op) {
		return op switch {
			Operator.DotDotDot => "...",
			Operator.DotDot => "..",
			Operator.ColonColon => "::",
			Operator.ReturnArrow => "->",
			Operator.Arrow => "=>",
			Operator.Fallback => "??",
			Operator.PlusPlus => "++",
			Operator.MinusMinus => "--",
			Operator.PlusEqual => "+=",
			Operator.MinusEqual => "-=",
			Operator.StarEqual => "*=",
			Operator.SlashEqual => "/=",
			Operator.PercentEqual => "%=",
			Operator.AndEqual => "&=",
			Operator.OrEqual => "|=",
			Operator.CaretEqual => "^=",
			Operator.EqualEqual => "==",
			Operator.NotEqual => "!=",
			Operator.LessEqual => "<=",
			Operator.GreaterEqual => ">=",
			Operator.Equal => "=",
			Operator.Less => "<",
			Operator.Greater => ">",
			Operator.Plus => "+",
			Operator.Minus => "-",
			Operator.Star => "*",
			Operator.Slash => "/",
			Operator.Percent => "%",
			Operator.And => "&",
			Operator.Or => "|",
			Operator.Caret => "^",
			Operator.Tilde => "~",
			Operator.Not => "!",
			Operator.Dot => ".",
			Operator.Comma => ",",
			Operator.Semicolon => ";",
			Operator.Colon => ":",
			Operator.LParen => "(",
			Operator.RParen => ")",
			Operator.LBrace => "{",
			Operator.RBrace => "}",
			Operator.LBracket => "[",
			Operator.RBracket => "]",
			Operator.At => "@",
			Operator.Hash => "#",
			Operator.Dollar => "$",
			Operator.Question => "?",
			Operator.Backtick => "`",
			_ => throw new NotImplementedException()
		};
	}
}